-- =====================================================================
-- 0058 — MMD: Material Movement & Data (a new KMR App)
--  • Raw material is issued from the RM store against a route sheet; every issue, every process and every supplier movement carries a QR tag.
--  • The route (process sequence) comes from the Operations Master › Cycle times (op no., machine, in-house or supplier process).
--  • Scan a tag → enter OK / rejection / rework for the next process → new tags (OK, one per rejection reason, one per rework reason) are printed.
--  • Supplier processes: a delivery challan (DC) with QR, and a goods-receipt note (GRN) by scanning it; good pieces continue on a new OK tag.
--  • Rejection and rework tags carry the reason code, the specification and the actual measured value (IATF 16949 8.7, ISO 9001 8.7).
--  • Loss hours are booked against D codes (Operations Master › Loss codes); records are never deleted — a wrong entry is voided with a reason (IATF 7.5.3, 8.5.2).
-- Needs 0057 (Operations Master lists for loss codes / reasons / shifts). Safe to re-run. Generated by scripts/make-mmd.py.
-- =====================================================================
do $$ begin
  if to_regprocedure('public.kmr_rmp_load(text,text)') is null then raise exception 'Run 0057_raw_material_planning.sql first.'; end if;
  if to_regprocedure('console.require_feature(text,text,text)') is null then raise exception 'Run 0056_feature_enforcement.sql first.'; end if;
end $$;

-- ---------- Operations Master: a route needs the operation number and whether a supplier does it (cycle-time list fields are free JSON) ----------
-- (nothing to alter: op_no, op_type and supplier are stored in the cycle-time record's data)

-- ---------- the product ----------
insert into console.products (code, name, description, app_path, seat_label, current_version, sort_order) values
  ('mmd', 'MMD — Material Movement', 'Shop-floor material movement with QR tags: RM issue, stage entry, rejection and rework, supplier DC and GRN, WIP and traceability', '/it/mmd.html', 'users', '1.0.0', 100)
on conflict (code) do nothing;
insert into console.releases (product_code, version, notes) values
  ('mmd', '1.0.0', 'MMD: RM issue with QR tag, route sheets, stage entry with rejection and rework tags, supplier DC and GRN, loss hours, WIP and traceability') on conflict do nothing;
insert into console.prices (product_code, period, currency, unit_amount, min_seats, active, note)
select v.code, v.period, 'INR', v.amt, 1, true, 'Starting price list (0058) — change in Console › Billing'
  from (values ('mmd', 'month', 4000), ('mmd', 'year', 40000)) v(code, period, amt)
on conflict (product_code, period, currency) do nothing;
insert into public.app_listings (code, name, tagline, features, sort_order, is_active) values
  ('mmd', 'MMD — Material Movement', 'Know where every part is: QR tags from raw material to finished goods, with rejection and rework captured at the source.',
   E'RM issue against a route sheet with heat code and QR tag\nScan → enter OK, rejection and rework → new QR tags, stage by stage\nSupplier process with DC and GRN; WIP map, loss hours and traceability for IATF 16949', 100, true)
on conflict (code) do update set name = excluded.name, tagline = coalesce(public.app_listings.tagline, excluded.tagline), features = coalesce(public.app_listings.features, excluded.features);

insert into console.app_features (product_code, name, detail, is_core, price_month, price_year, setup_fee, sort_order) values
  ('mmd', 'RM issue, route sheet & QR tags', 'Issue raw material with heat code against a route sheet; stage entry (OK / rejection / rework) with a new QR tag at every stage up to finished goods', true, 1500, 0, 25000, 10),
  ('mmd', 'Supplier DC & GRN', 'Delivery challan with QR for supplier processes; receipt by scanning the DC, good pieces continue on a new tag', false, 600, 0, 8000, 20),
  ('mmd', 'Loss hours (D codes)', 'Machine-wise loss hours booked against the loss codes of the Operations Master', false, 500, 0, 6000, 30),
  ('mmd', 'WIP map & throughput alerts', 'Where every part lies, with quantity; alert when material stops moving against the throughput time', false, 700, 0, 10000, 40),
  ('mmd', 'Dashboards & Pareto', 'Production efficiency, OEE, capacity utilisation, rejection and rework rate; Pareto by part, defect, process, machine and operator', false, 900, 0, 15000, 50),
  ('mmd', 'Traceability & IATF records', 'Heat code to customer trace in both directions, entry voiding with reason, record export', false, 500, 0, 8000, 60)
on conflict (product_code, name) do nothing;
delete from console.app_features f where f.product_code = 'mmd' and f.name = 'Core platform'
   and not exists (select 1 from console.invoice_lines il where il.feature_id = f.id);
update console.app_features set price_year = price_month * 10 where product_code = 'mmd' and price_year = 0;
select console.sync_app_price('mmd');

-- ---------- tables ----------
create table if not exists console.mmd_counters (
  customer_id uuid not null references console.customers(id) on delete cascade, key text not null, n bigint not null default 0, sample boolean not null default false, primary key (customer_id, key));
create table if not exists console.mmd_route_sheets (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  rs_no text not null, part_code text not null, part_name text, customer_name text, qty numeric not null check (qty > 0),
  ops jsonb not null default '[]',                                  -- the process sequence at the time of issue: [{seq, op_no, name, machine, type: in|supplier, supplier, ct_sec}]
  rm_material text, rm_spec text, rm_size text, heat_code text, rm_kg numeric, mill_cert text, due_date date,
  status text not null default 'open' check (status in ('open', 'closed', 'cancelled')), notes text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(), closed_at timestamptz,
  unique (customer_id, rs_no));
create table if not exists console.mmd_tags (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  tag_no text not null, rs_id uuid not null references console.mmd_route_sheets(id) on delete cascade,
  kind text not null check (kind in ('RM', 'OK', 'REJ', 'REW')),
  seq int,                                       -- the operation this tag waits for (REW: the operation the rework belongs to); null at finished goods / rejection
  loc text not null check (loc in ('op', 'supplier', 'fg', 'rejection', 'rework', 'dispatched', 'closed')),
  qty numeric not null check (qty > 0), bal numeric not null check (bal >= 0),
  status text not null default 'open' check (status in ('open', 'used', 'void')),
  parent_tag uuid references console.mmd_tags(id), op_done int, entry_id uuid,
  reason_code text, reason text, spec text, actual text,
  dispo text, dispo_by text, dispo_at timestamptz, dispo_note text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(),
  unique (customer_id, tag_no));
create table if not exists console.mmd_entries (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  rs_id uuid not null references console.mmd_route_sheets(id) on delete cascade, tag_id uuid references console.mmd_tags(id), dc_id uuid,
  kind text not null check (kind in ('process', 'rework', 'dc', 'grn', 'dispatch')),
  seq int, op_name text, machine text, ok_qty numeric not null default 0, rej_qty numeric not null default 0, rew_qty numeric not null default 0,
  entry_at timestamptz not null default now(), shift text, operator text, engineer text, note text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text, void_by text, void_at timestamptz,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create table if not exists console.mmd_defects (       -- one row per rejection / rework reason line: the source of the Pareto charts and of the rejection and rework tags
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  entry_id uuid not null references console.mmd_entries(id) on delete cascade, rs_id uuid not null, tag_id uuid,
  kind text not null check (kind in ('rej', 'rew')), reason_code text, reason text, qty numeric not null check (qty > 0), spec text, actual text,
  part_code text, op_name text, machine text, operator text, entry_at timestamptz not null, void boolean not null default false, sample boolean not null default false);
create table if not exists console.mmd_dcs (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  dc_no text not null, rs_id uuid not null references console.mmd_route_sheets(id) on delete cascade, tag_id uuid references console.mmd_tags(id), seq int not null, op_name text,
  supplier_code text, supplier_name text, qty numeric not null check (qty > 0), received_qty numeric not null default 0, vehicle text, dispatch_at timestamptz not null default now(), expected_date date,
  status text not null default 'open' check (status in ('open', 'part', 'closed', 'cancelled')), note text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(),
  unique (customer_id, dc_no));
create table if not exists console.mmd_grns (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  grn_no text not null, dc_id uuid not null references console.mmd_dcs(id) on delete cascade, rs_id uuid not null, entry_id uuid,
  ok_qty numeric not null default 0, rej_qty numeric not null default 0, inv_no text, received_at timestamptz not null default now(), note text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(),
  unique (customer_id, grn_no));
create table if not exists console.mmd_loss (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  loss_date date not null, shift text, machine_code text not null, d_code text not null, d_name text, minutes numeric not null check (minutes > 0 and minutes <= 1440),
  rs_id uuid, part_code text, op_name text, remark text, operator text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create index if not exists mmd_tags_open on console.mmd_tags (customer_id, status, loc);
create index if not exists mmd_tags_rs on console.mmd_tags (rs_id);
create index if not exists mmd_entries_rs on console.mmd_entries (rs_id, seq);
create index if not exists mmd_entries_at on console.mmd_entries (customer_id, entry_at);
create index if not exists mmd_defects_at on console.mmd_defects (customer_id, entry_at);
create index if not exists mmd_loss_date on console.mmd_loss (customer_id, loss_date);
do $$ declare t text; begin foreach t in array array['mmd_counters','mmd_route_sheets','mmd_tags','mmd_entries','mmd_defects','mmd_dcs','mmd_grns','mmd_loss'] loop
  execute format('alter table console.%I enable row level security', t);
  execute format('drop policy if exists %I on console.%I', t || '_staff', t);
  execute format('create policy %I on console.%I for all to authenticated using (console.is_staff()) with check (console.is_staff())', t || '_staff', t);
end loop; end $$;

--@@CORE@@
--@@REGENERATED@@
