-- =====================================================================
-- 0059 — Maintenance (a new KMR App)
--  • Breakdown log per machine: reported → attended → restored, with root cause, corrective and preventive action, spares used (IATF 16949 8.5.1.5, ISO 9001 7.1.3).
--  • Machine downtime analysis, MTBF, MTTR, availability, repeat failures; preventive-maintenance schedule with compliance.
--  • Machine history card: master data + every breakdown, PM and modification, printable (IATF 16949 8.5.1.5 / ISO 9001 7.1.3 / 7.5.3 documented information).
--  • A closed breakdown books its downtime in MMD loss hours against the chosen D code, so the loss is typed once.
-- Needs 0058 (MMD). Safe to re-run. Generated by scripts/make-mnt.py.
-- =====================================================================
do $$ begin
  if to_regprocedure('public.kmr_mmd_load(text)') is null then raise exception 'Run 0058_mmd.sql first.'; end if;
end $$;

insert into console.products (code, name, description, app_path, seat_label, current_version, sort_order) values
  ('mnt', 'Maintenance', 'Breakdown log, downtime analysis, MTBF and MTTR, preventive maintenance plan and the machine history card', '/it/mnt.html', 'users', '1.0.0', 110)
on conflict (code) do nothing;
insert into console.releases (product_code, version, notes) values
  ('mnt', '1.0.0', 'Maintenance: breakdown log, downtime analysis, MTBF / MTTR, preventive maintenance plan, machine history card') on conflict do nothing;
insert into console.prices (product_code, period, currency, unit_amount, min_seats, active, note)
select v.code, v.period, 'INR', v.amt, 1, true, 'Starting price list (0059) — change in Console › Billing'
  from (values ('mnt', 'month', 3000), ('mnt', 'year', 30000)) v(code, period, amt)
on conflict (product_code, period, currency) do nothing;
insert into public.app_listings (code, name, tagline, features, sort_order, is_active) values
  ('mnt', 'Maintenance', 'Fewer breakdowns, faster repairs: every stoppage logged, analysed and linked to the machine history card.',
   E'Breakdown log with root cause, corrective and preventive action\nMTBF, MTTR, availability and downtime Pareto per machine\nPreventive maintenance schedule and printable machine history card for IATF 16949', 110, true)
on conflict (code) do update set name = excluded.name, tagline = coalesce(public.app_listings.tagline, excluded.tagline), features = coalesce(public.app_listings.features, excluded.features);

insert into console.app_features (product_code, name, detail, is_core, price_month, price_year, setup_fee, sort_order) values
  ('mnt', 'Breakdown log & downtime', 'Report, attend and close breakdowns with root cause, action and spares; downtime flows to MMD loss hours', true, 1200, 0, 15000, 10),
  ('mnt', 'Preventive maintenance plan', 'PM schedule per machine from the Operations Master PM frequency, due / overdue list, completion records and compliance', false, 700, 0, 8000, 20),
  ('mnt', 'MTTR, MTBF & analysis', 'MTBF, MTTR and availability per machine, downtime Pareto by machine and cause, repeat failures, monthly trend', false, 800, 0, 10000, 30),
  ('mnt', 'Machine history card', 'Printable card per machine: master data, breakdowns, PM and modifications, with its own MTBF and MTTR', false, 500, 0, 6000, 40)
on conflict (product_code, name) do nothing;
delete from console.app_features f where f.product_code = 'mnt' and f.name = 'Core platform'
   and not exists (select 1 from console.invoice_lines il where il.feature_id = f.id);
update console.app_features set price_year = price_month * 10 where product_code = 'mnt' and price_year = 0;
select console.sync_app_price('mnt');

-- a closed breakdown books its downtime in MMD loss hours; the link is the breakdown number
alter table console.mmd_loss add column if not exists ref text;

create table if not exists console.mnt_counters (
  customer_id uuid not null references console.customers(id) on delete cascade, key text not null, n bigint not null default 0, primary key (customer_id, key));
create table if not exists console.mnt_breakdowns (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  bd_no text not null, machine_code text not null, machine_name text,
  started_at timestamptz not null, attended_at timestamptz, ended_at timestamptz, shift text, reported_by text, attended_by text,
  problem text not null, category text, d_code text, root_cause text, action_taken text, preventive_action text, spares jsonb not null default '[]',
  status text not null default 'open' check (status in ('open', 'attended', 'closed', 'void')), void_reason text, closed_by text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(),
  unique (customer_id, bd_no));
create table if not exists console.mnt_pm_plans (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  machine_code text not null, machine_name text, task text not null, frequency_days int not null check (frequency_days between 1 and 1100), est_min int,
  last_done date, next_due date not null, active boolean not null default true, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create table if not exists console.mnt_pm_log (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  plan_id uuid references console.mnt_pm_plans(id) on delete set null, machine_code text not null, task text not null,
  done_on date not null, due_on date, done_by text, duration_min int, findings text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create table if not exists console.mnt_events (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  machine_code text not null, event_date date not null, type text not null, description text not null, cost numeric, done_by text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create index if not exists mnt_bd_machine on console.mnt_breakdowns (customer_id, machine_code, started_at);
create index if not exists mnt_pm_due on console.mnt_pm_plans (customer_id, next_due);
create index if not exists mnt_log_machine on console.mnt_pm_log (customer_id, machine_code, done_on);
create index if not exists mnt_ev_machine on console.mnt_events (customer_id, machine_code, event_date);
do $$ declare t text; begin foreach t in array array['mnt_counters','mnt_breakdowns','mnt_pm_plans','mnt_pm_log','mnt_events'] loop
  execute format('alter table console.%I enable row level security', t);
  execute format('drop policy if exists %I on console.%I', t || '_staff', t);
  execute format('create policy %I on console.%I for all to authenticated using (console.is_staff()) with check (console.is_staff())', t || '_staff', t);
end loop; end $$;

--@@CORE@@
--@@REGENERATED@@
