-- =====================================================================
-- 0057 — Raw Material Planning (a new KMR App)
--  • Reads the Operations Master: parts (with their material and weight), raw materials (grade, supplier, rate), suppliers.
--  • Parts to start comes from the Capacity Planner (published each time the plan is saved) — or is typed by hand for a month.
--  • Per part: kg of which material one piece needs (default: the part's weight; override per part with a bill of material and a loss %).
--  • Per material: stock on hand, safety stock, lead time, minimum order, pack size.
--  • Result: what to buy, how much (net of stock and open orders, rounded to MOQ / pack), the latest order date, per supplier, with value.
--  • Orders: planned → ordered → received; receiving adds to the stock.
--  • Joins the portal (card, access, figures), the Data Master and the Grand Master (sample load / flush / backup).
-- Needs 0050, 0051 and 0053–0056. Safe to re-run. Generated by scripts/make-rmp.py.
-- =====================================================================
do $$ begin
  if to_regprocedure('public.kmr_grand_sample(text,text)') is null then raise exception 'Run 0043–0048 first.'; end if;
  if to_regclass('console.app_features') is null then raise exception 'Run 0050_app_features.sql first.'; end if;
  if to_regprocedure('console.require_feature(text,text,text)') is null then raise exception 'Run 0056_feature_enforcement.sql first.'; end if;
  if to_regprocedure('public.cp_my_role(uuid)') is null then raise exception 'Run 0010_capacity.sql first.'; end if;
end $$;

-- ---------- the product ----------
insert into console.products (code, name, description, app_path, seat_label, current_version, sort_order) values
  ('rmp', 'Raw Material Planning', 'What to buy, how much and by when: parts to start from the Capacity Planner turned into raw material, net of stock and open orders, per supplier', '/it/rmp.html', 'users', '1.0.0', 90)
on conflict (code) do nothing;
insert into console.releases (product_code, version, notes) values
  ('rmp', '1.0.0', 'Raw Material Planning: requirement from the Capacity Planner, bill of material, stock, MOQ and lead time, purchase plan, supplier orders') on conflict do nothing;
insert into console.prices (product_code, period, currency, unit_amount, min_seats, active, note)
select v.code, v.period, 'INR', v.amt, 1, true, 'Starting price list (0057) — change in Console › Billing'
  from (values ('rmp', 'month', 2000), ('rmp', 'year', 20000)) v(code, period, amt)
on conflict (product_code, period, currency) do nothing;
insert into public.app_listings (code, name, tagline, features, sort_order, is_active) values
  ('rmp', 'Raw Material Planning', 'Know what raw material to buy, how much, from whom and by when — straight from your capacity plan.',
   E'Parts to start from the Capacity Planner turned into kg of every material\nNet of stock and open orders, rounded to minimum order and pack size\nLatest order date from the lead time; orders per supplier with value', 90, true)
on conflict (code) do update set name = excluded.name, tagline = coalesce(public.app_listings.tagline, excluded.tagline), features = coalesce(public.app_listings.features, excluded.features);

-- ---------- features (what a quotation / invoice can switch on) ----------
insert into console.app_features (product_code, name, detail, is_core, price_month, price_year, setup_fee, sort_order) values
  ('rmp', 'Material requirement from capacity plan', 'Parts to start × material per part = kg needed, compared with stock', true, 300, 0, 12000, 10),
  ('rmp', 'Purchase plan, MOQ & lead times', 'Net buy quantity rounded to minimum order and pack, latest order date, safety stock and value', false, 250, 0, 8000, 20),
  ('rmp', 'Supplier orders & receipts', 'Orders per supplier: planned, ordered, received — receipts update the stock', false, 200, 0, 6000, 30)
on conflict (product_code, name) do nothing;
delete from console.app_features f where f.product_code = 'rmp' and f.name = 'Core platform'
   and not exists (select 1 from console.invoice_lines il where il.feature_id = f.id);
update console.app_features set price_year = price_month * 10 where product_code = 'rmp' and price_year = 0;
select console.sync_app_price('rmp');

-- ---------- tables ----------
create table if not exists console.rmp_bom (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  part_code text not null, material_code text not null,
  rm_kg numeric check (rm_kg is null or rm_kg >= 0),            -- raw material per piece before loss; blank = the part's weight from the Operations Master
  loss_pct numeric not null default 0 check (loss_pct >= 0 and loss_pct < 100),   -- bar end, parting, chips, forging flash — on top of rm_kg
  notes text, sample boolean not null default false, updated_by text, updated_at timestamptz not null default now(),
  unique (customer_id, part_code, material_code));
create table if not exists console.rmp_stock (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  material_code text not null,
  on_hand_kg numeric not null default 0 check (on_hand_kg >= 0), safety_kg numeric not null default 0 check (safety_kg >= 0),
  lead_days int check (lead_days is null or lead_days >= 0), moq_kg numeric check (moq_kg is null or moq_kg >= 0), pack_kg numeric check (pack_kg is null or pack_kg >= 0),
  sample boolean not null default false, updated_by text, updated_at timestamptz not null default now(),
  unique (customer_id, material_code));
create table if not exists console.rmp_demand (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'), part_code text not null,
  start_qty numeric not null check (start_qty >= 0), sales_qty numeric, need_by date,
  source text not null default 'capacity' check (source in ('capacity', 'manual')),       -- manual wins: a published plan never overwrites a typed quantity
  sample boolean not null default false, published_by text, published_at timestamptz not null default now(),
  unique (customer_id, month, part_code));
create table if not exists console.rmp_orders (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  material_code text not null, supplier_code text, month text, po_no text,
  qty_kg numeric not null check (qty_kg > 0), rate numeric, order_date date, due_date date,
  status text not null default 'planned' check (status in ('planned', 'ordered', 'received', 'cancelled')),
  received_kg numeric, received_on date, notes text,
  sample boolean not null default false, updated_by text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists rmp_orders_customer on console.rmp_orders (customer_id, status, material_code);
create index if not exists rmp_demand_month on console.rmp_demand (customer_id, month);
do $$ declare t text; begin foreach t in array array['rmp_bom','rmp_stock','rmp_demand','rmp_orders'] loop
  execute format('alter table console.%I enable row level security', t);
  execute format('drop policy if exists %I on console.%I', t || '_staff', t);
  execute format('create policy %I on console.%I for all to authenticated using (console.is_staff()) with check (console.is_staff())', t || '_staff', t);
end loop; end $$;

-- ---------- access: same roles as APQP / PPAP (Administration › Users & access) ----------
create or replace function public.kmr_rmp_context(p_slug text) returns jsonb language sql stable security definer set search_path = console, public as $$
  select case when console.qp_role(c.id, 'rmp') is null then null else jsonb_build_object('role', console.qp_role(c.id, 'rmp'), 'company', c.name) end
    from console.customers c where c.slug = lower(p_slug) $$;
grant execute on function public.kmr_rmp_context(text) to authenticated;

-- everything the screens need for one month, in one call
create or replace function public.kmr_rmp_load(p_slug text, p_month text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.qp_cid(p_slug, 'rmp'); cap boolean;
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then raise exception 'Month must look like 2026-10.'; end if;
  cap := exists (select 1 from console.licences where customer_id = cid and product_code = 'capacity' and product_ref is not null);
  return jsonb_build_object(
    'parts', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'parts' and r.active), '[]'),
    'materials', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'raw_materials' and r.active), '[]'),
    'suppliers', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'suppliers' and r.active), '[]'),
    'bom', coalesce((select jsonb_agg(to_jsonb(b) - 'customer_id' order by b.part_code, b.material_code) from console.rmp_bom b where b.customer_id = cid), '[]'),
    'stock', coalesce((select jsonb_agg(to_jsonb(s) - 'customer_id' order by s.material_code) from console.rmp_stock s where s.customer_id = cid), '[]'),
    'demand', coalesce((select jsonb_agg(to_jsonb(d) - 'customer_id' order by d.part_code) from console.rmp_demand d where d.customer_id = cid and d.month = p_month), '[]'),
    'months', coalesce((select jsonb_agg(m order by m desc) from (select distinct month m from console.rmp_demand where customer_id = cid) x), '[]'),
    'orders', coalesce((select jsonb_agg(to_jsonb(o) - 'customer_id' order by o.created_at desc) from console.rmp_orders o
                         where o.customer_id = cid and (o.status in ('planned', 'ordered') or o.updated_at > now() - interval '120 days')), '[]'),
    'capacity', cap,
    'today', (now() at time zone 'Asia/Kolkata')::date);
end $$;
grant execute on function public.kmr_rmp_load(text, text) to authenticated;

-- ---------- bill of material ----------
create or replace function public.kmr_rmp_bom_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid; pc text := trim(coalesce(p ->> 'part_code', '')); mc text := trim(coalesce(p ->> 'material_code', ''));
begin
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'parts' and code = pc) then raise exception 'Part % is not in Operations Master › Parts.', pc; end if;
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  insert into console.rmp_bom (customer_id, part_code, material_code, rm_kg, loss_pct, notes, updated_by)
  values (cid, pc, mc, nullif(p ->> 'rm_kg', '')::numeric, coalesce(nullif(p ->> 'loss_pct', '')::numeric, 0), nullif(p ->> 'notes', ''), lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (customer_id, part_code, material_code) do update set rm_kg = excluded.rm_kg, loss_pct = excluded.loss_pct, notes = excluded.notes, updated_by = excluded.updated_by, updated_at = now(), sample = false
  returning id into rid;
  return rid;
end $$;
create or replace function public.kmr_rmp_bom_delete(p_slug text, p_id uuid) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin delete from console.rmp_bom where id = p_id and customer_id = cid; end $$;
grant execute on function public.kmr_rmp_bom_save(text, jsonb), public.kmr_rmp_bom_delete(text, uuid) to authenticated;

-- ---------- stock and planning data per material ----------
create or replace function public.kmr_rmp_stock_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid; mc text := trim(coalesce(p ->> 'material_code', ''));
begin
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  insert into console.rmp_stock (customer_id, material_code, on_hand_kg, safety_kg, lead_days, moq_kg, pack_kg, updated_by)
  values (cid, mc, coalesce(nullif(p ->> 'on_hand_kg', '')::numeric, 0), coalesce(nullif(p ->> 'safety_kg', '')::numeric, 0), nullif(p ->> 'lead_days', '')::int,
          nullif(p ->> 'moq_kg', '')::numeric, nullif(p ->> 'pack_kg', '')::numeric, lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (customer_id, material_code) do update set
    on_hand_kg = case when p ? 'on_hand_kg' then excluded.on_hand_kg else console.rmp_stock.on_hand_kg end,
    safety_kg = case when p ? 'safety_kg' then excluded.safety_kg else console.rmp_stock.safety_kg end,
    lead_days = case when p ? 'lead_days' then excluded.lead_days else console.rmp_stock.lead_days end,
    moq_kg = case when p ? 'moq_kg' then excluded.moq_kg else console.rmp_stock.moq_kg end,
    pack_kg = case when p ? 'pack_kg' then excluded.pack_kg else console.rmp_stock.pack_kg end,
    updated_by = excluded.updated_by, updated_at = now(), sample = false
  returning id into rid;
  return rid;
end $$;
grant execute on function public.kmr_rmp_stock_save(text, jsonb) to authenticated;

-- ---------- parts to start: typed by hand (a typed quantity is never overwritten by the Capacity Planner) ----------
create or replace function public.kmr_rmp_demand_save(p_slug text, p_month text, p_rows jsonb) returns integer
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); r jsonb; n int := 0;
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then raise exception 'Month must look like 2026-10.'; end if;
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'parts' and code = trim(coalesce(r ->> 'part_code', ''))) then
      raise exception 'Part % is not in Operations Master › Parts.', r ->> 'part_code';
    end if;
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, need_by, source, published_by)
    values (cid, p_month, trim(r ->> 'part_code'), greatest(0, coalesce(nullif(r ->> 'start_qty', '')::numeric, 0)), nullif(r ->> 'need_by', '')::date, 'manual', lower(coalesce(auth.jwt() ->> 'email', '')))
    on conflict (customer_id, month, part_code) do update set start_qty = excluded.start_qty, need_by = excluded.need_by, source = 'manual', published_by = excluded.published_by, published_at = now(), sample = false;
    n := n + 1;
  end loop;
  return n;
end $$;
-- hand the part back to the Capacity Planner (the typed quantity is removed; the next save of the plan publishes it again)
create or replace function public.kmr_rmp_demand_clear(p_slug text, p_month text, p_part text) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin delete from console.rmp_demand where customer_id = cid and month = p_month and part_code = p_part; end $$;
grant execute on function public.kmr_rmp_demand_save(text, text, jsonb), public.kmr_rmp_demand_clear(text, text, text) to authenticated;

-- ---------- the Capacity Planner publishes its parts to start (called after every save of the plan; silent when the company has no Raw Material Planning) ----------
create or replace function public.kmr_rmp_publish(p_org uuid, p_month text, p_rows jsonb) returns integer
language plpgsql security definer set search_path = console, public as $$
declare cid uuid; r jsonb; n int := 0; me text := lower(coalesce(auth.jwt() ->> 'email', '')); keep text[] := '{}';
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then return 0; end if;
  select l.customer_id into cid from console.licences l where l.product_code = 'capacity' and l.product_ref = p_org limit 1;
  if cid is null or not exists (select 1 from console.licences where customer_id = cid and product_code = 'rmp') then return 0; end if;
  if not coalesce((select ok from console.access_state('rmp', cid)), false) then return 0; end if;
  if coalesce(public.cp_my_role(p_org), '') not in ('admin', 'editor') then return 0; end if;
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    continue when coalesce(r ->> 'part_code', '') = '';
    keep := keep || (r ->> 'part_code');
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, sales_qty, need_by, source, published_by)
    values (cid, p_month, r ->> 'part_code', greatest(0, coalesce(nullif(r ->> 'start_qty', '')::numeric, 0)), nullif(r ->> 'sales_qty', '')::numeric, nullif(r ->> 'need_by', '')::date, 'capacity', me)
    on conflict (customer_id, month, part_code) do update set start_qty = excluded.start_qty, sales_qty = excluded.sales_qty, need_by = excluded.need_by, published_by = excluded.published_by, published_at = now(), sample = false
      where console.rmp_demand.source = 'capacity';
    n := n + 1;
  end loop;
  delete from console.rmp_demand where customer_id = cid and month = p_month and source = 'capacity' and not (part_code = any (keep));   -- parts that left the plan
  return n;
end $$;
grant execute on function public.kmr_rmp_publish(uuid, text, jsonb) to authenticated;

-- ---------- orders ----------
create or replace function public.kmr_rmp_order_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid := nullif(p ->> 'id', '')::uuid; mc text := trim(coalesce(p ->> 'material_code', '')); st text;
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  if coalesce(nullif(p ->> 'qty_kg', '')::numeric, 0) <= 0 then raise exception 'Enter the quantity in kg.'; end if;
  if rid is null then
    insert into console.rmp_orders (customer_id, material_code, supplier_code, month, po_no, qty_kg, rate, order_date, due_date, status, notes, updated_by)
    values (cid, mc, nullif(p ->> 'supplier_code', ''), nullif(p ->> 'month', ''), nullif(p ->> 'po_no', ''), (p ->> 'qty_kg')::numeric, nullif(p ->> 'rate', '')::numeric,
            nullif(p ->> 'order_date', '')::date, nullif(p ->> 'due_date', '')::date, case when p ->> 'status' = 'ordered' then 'ordered' else 'planned' end, nullif(p ->> 'notes', ''), lower(coalesce(auth.jwt() ->> 'email', '')))
    returning id into rid;
  else
    select status into st from console.rmp_orders where id = rid and customer_id = cid;
    if st is null then raise exception 'Unknown order.'; end if;
    if st in ('received', 'cancelled') then raise exception 'A % order cannot be changed.', st; end if;
    update console.rmp_orders set supplier_code = nullif(p ->> 'supplier_code', ''), po_no = nullif(p ->> 'po_no', ''), qty_kg = (p ->> 'qty_kg')::numeric, rate = nullif(p ->> 'rate', '')::numeric,
           order_date = nullif(p ->> 'order_date', '')::date, due_date = nullif(p ->> 'due_date', '')::date, notes = nullif(p ->> 'notes', ''),
           updated_by = lower(coalesce(auth.jwt() ->> 'email', '')), updated_at = now(), sample = false
     where id = rid and customer_id = cid;
  end if;
  return rid;
end $$;
-- planned → ordered → received (the received kg is added to the stock) · or cancelled
create or replace function public.kmr_rmp_order_status(p_slug text, p_id uuid, p_status text, p_received_kg numeric default null) returns text
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); o console.rmp_orders%rowtype; today date := (now() at time zone 'Asia/Kolkata')::date; kg numeric;
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  select * into o from console.rmp_orders where id = p_id and customer_id = cid for update;
  if o.id is null then raise exception 'Unknown order.'; end if;
  if p_status not in ('ordered', 'received', 'cancelled') then raise exception 'Unknown status.'; end if;
  if o.status in ('received', 'cancelled') then raise exception 'This order is already %.', o.status; end if;
  if p_status = 'ordered' then
    update console.rmp_orders set status = 'ordered', order_date = coalesce(order_date, today), updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
  elsif p_status = 'cancelled' then
    update console.rmp_orders set status = 'cancelled', updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
  else
    kg := coalesce(p_received_kg, o.qty_kg);
    if kg <= 0 then raise exception 'Enter the quantity received.'; end if;
    update console.rmp_orders set status = 'received', received_kg = kg, received_on = today, updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
    insert into console.rmp_stock (customer_id, material_code, on_hand_kg, updated_by) values (cid, o.material_code, kg, lower(coalesce(auth.jwt() ->> 'email', '')))
    on conflict (customer_id, material_code) do update set on_hand_kg = console.rmp_stock.on_hand_kg + kg, updated_at = now(), updated_by = excluded.updated_by;
  end if;
  return p_status;
end $$;
create or replace function public.kmr_rmp_order_delete(p_slug text, p_id uuid) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  delete from console.rmp_orders where id = p_id and customer_id = cid and status = 'planned';
end $$;
grant execute on function public.kmr_rmp_order_save(text, jsonb), public.kmr_rmp_order_status(text, uuid, text, numeric), public.kmr_rmp_order_delete(text, uuid) to authenticated;

-- ---------- sample data: built from the Operations Master sample parts and raw materials ----------
create or replace function console.rmp_sample(p_cid uuid, p_action text) returns integer language plpgsql security definer set search_path = console, public as $$
declare today date := (now() at time zone 'Asia/Kolkata')::date; mth text := to_char((now() at time zone 'Asia/Kolkata')::date, 'YYYY-MM'); n int := 0; k int := 0; p record; m record;
begin
  if p_action = 'flush' then
    delete from console.rmp_orders where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_demand where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_bom where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_stock where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    return n;
  end if;
  if exists (select 1 from console.rmp_stock where customer_id = p_cid and sample) then return 0; end if;
  -- stock, safety stock, lead time, MOQ and pack for every sample raw material
  for m in select r.code, r.data, row_number() over (order by r.code) rn from console.ops_records r where r.customer_id = p_cid and r.kind = 'raw_materials' and r.sample and r.active loop
    insert into console.rmp_stock (customer_id, material_code, on_hand_kg, safety_kg, lead_days, moq_kg, pack_kg, sample, updated_by)
    values (p_cid, m.code, (array[2400, 5200, 900, 3100, 1800, 4200, 2600])[1 + (m.rn - 1) % 7], (array[800, 1500, 400, 1000, 600, 1200, 900])[1 + (m.rn - 1) % 7],
            case m.data ->> 'form' when 'Bar' then 10 when 'Forging' then 21 else 28 end, case m.data ->> 'form' when 'Bar' then 1000 else 2000 end, case m.data ->> 'form' when 'Bar' then 250 else 500 end, true, 'sample');
    n := n + 1;
  end loop;
  -- parts to start this month (as the Capacity Planner would publish them) and a bill of material with a loss % on the bar parts
  for p in select r.code, r.data, row_number() over (order by r.code) rn from console.ops_records r where r.customer_id = p_cid and r.kind = 'parts' and r.sample and r.active loop
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, sales_qty, need_by, source, sample, published_by)
    values (p_cid, mth, p.code, round((coalesce((p.data ->> 'annual_volume')::numeric, 12000) / 12) * (0.9 + (p.rn % 4) * 0.08) / 10) * 10,
            round(coalesce((p.data ->> 'annual_volume')::numeric, 12000) / 12 / 10) * 10, today + (3 + (p.rn * 2) % 21)::int, 'capacity', true, 'sample');
    n := n + 1;
    if p.rn % 3 = 0 and p.data ->> 'material' is not null then
      insert into console.rmp_bom (customer_id, part_code, material_code, rm_kg, loss_pct, notes, sample, updated_by)
      values (p_cid, p.code, p.data ->> 'material', null, 4, 'Bar end and parting loss', true, 'sample') on conflict do nothing;
      n := n + 1;
    end if;
  end loop;
  -- two orders placed, one received
  insert into console.rmp_orders (customer_id, material_code, supplier_code, month, po_no, qty_kg, rate, order_date, due_date, status, received_kg, received_on, sample, updated_by)
  select p_cid, r.code, r.data ->> 'supplier', mth, 'PO-' || to_char(today, 'YY') || '-' || lpad((100 + o.k)::text, 4, '0'), o.qty, nullif(r.data ->> 'rate_per_kg', '')::numeric, today - o.ago, today - o.ago + 14, o.st,
         case when o.st = 'received' then o.qty end, case when o.st = 'received' then today - 2 end, true, 'sample'
    from (values (1, 'RM-EN8-65', 3000, 12, 'ordered'), (2, 'RM-EN353-F', 2000, 9, 'ordered'), (3, 'RM-EN19-45', 1000, 20, 'received')) o(k, code, qty, ago, st)
    join console.ops_records r on r.customer_id = p_cid and r.kind = 'raw_materials' and r.code = o.code and r.sample;
  get diagnostics k = row_count; n := n + k;
  return n;
end $$;
revoke all on function console.rmp_sample(uuid, text) from public, anon, authenticated;

-- ---------- portal, access, Data Master and Grand Master: every function re-created from its latest version with Raw Material Planning added ----------
--@@REGENERATED@@

-- the app's functions join the same execute grants as the other apps
do $$ declare f record; begin
  for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname ~ '^kmr_rmp_' loop
    execute format('revoke all on function %s from public, anon', f.sig);
    execute format('grant execute on function %s to authenticated', f.sig);
  end loop;
end $$;
