-- =====================================================================
-- 0057 — Raw Material Planning (a new KMR App)
--  • Reads the Operations Master: parts (with their material and weight), raw materials (grade, supplier, rate), suppliers.
--  • Parts to start comes from the Capacity Planner (published each time the plan is saved) — or is typed by hand for a month.
--  • Per part: kg of which material one piece needs (default: the part's weight; override per part with a bill of material and a loss %).
--  • Per material: stock on hand, safety stock, lead time, minimum order, pack size.
--  • Result: what to buy, how much (net of stock and open orders, rounded to MOQ / pack), the latest order date, per supplier, with value.
--  • Orders: planned → ordered → received; receiving adds to the stock.
--  • Joins the portal (card, access, figures), the Data Master and the Grand Master (sample load / flush / backup).
-- Needs 0050, 0051 and 0053–0056. Safe to re-run. Generated by scripts/make-rmp.py.
-- =====================================================================
do $$ begin
  if to_regprocedure('public.kmr_grand_sample(text,text)') is null then raise exception 'Run 0043–0048 first.'; end if;
  if to_regclass('console.app_features') is null then raise exception 'Run 0050_app_features.sql first.'; end if;
  if to_regprocedure('console.require_feature(text,text,text)') is null then raise exception 'Run 0056_feature_enforcement.sql first.'; end if;
  if to_regprocedure('public.cp_my_role(uuid)') is null then raise exception 'Run 0010_capacity.sql first.'; end if;
end $$;

-- ---------- Operations Master: new lists (bill of material, loss codes, defect codes, shifts) ----------
alter table console.ops_records drop constraint if exists ops_records_kind_check;
alter table console.ops_records add constraint ops_records_kind_check check (kind in ('parts','customers','suppliers','machines','gauges','tools',
  'consumables','raw_materials','rate_contracts','cycle_times','cft','documents','plant_standards','bom','loss_codes','defect_codes','shifts'));

-- ---------- the product ----------
insert into console.products (code, name, description, app_path, seat_label, current_version, sort_order) values
  ('rmp', 'Raw Material Planning', 'What to buy, how much and by when: parts to start from the Capacity Planner turned into raw material, net of stock and open orders, per supplier', '/it/rmp.html', 'users', '1.0.0', 90)
on conflict (code) do nothing;
insert into console.releases (product_code, version, notes) values
  ('rmp', '1.0.0', 'Raw Material Planning: requirement from the Capacity Planner, bill of material, stock, MOQ and lead time, purchase plan, supplier orders') on conflict do nothing;
insert into console.prices (product_code, period, currency, unit_amount, min_seats, active, note)
select v.code, v.period, 'INR', v.amt, 1, true, 'Starting price list (0057) — change in Console › Billing'
  from (values ('rmp', 'month', 2000), ('rmp', 'year', 20000)) v(code, period, amt)
on conflict (product_code, period, currency) do nothing;
insert into public.app_listings (code, name, tagline, features, sort_order, is_active) values
  ('rmp', 'Raw Material Planning', 'Know what raw material to buy, how much, from whom and by when — straight from your capacity plan.',
   E'Parts to start from the Capacity Planner turned into kg of every material\nNet of stock and open orders, rounded to minimum order and pack size\nLatest order date from the lead time; orders per supplier with value', 90, true)
on conflict (code) do update set name = excluded.name, tagline = coalesce(public.app_listings.tagline, excluded.tagline), features = coalesce(public.app_listings.features, excluded.features);

-- ---------- features (what a quotation / invoice can switch on) ----------
insert into console.app_features (product_code, name, detail, is_core, price_month, price_year, setup_fee, sort_order) values
  ('rmp', 'Material requirement from capacity plan', 'Parts to start × material per part = kg needed, compared with stock', true, 300, 0, 12000, 10),
  ('rmp', 'Purchase plan, MOQ & lead times', 'Net buy quantity rounded to minimum order and pack, latest order date, safety stock and value', false, 250, 0, 8000, 20),
  ('rmp', 'Supplier orders & receipts', 'Orders per supplier: planned, ordered, received — receipts update the stock', false, 200, 0, 6000, 30)
on conflict (product_code, name) do nothing;
delete from console.app_features f where f.product_code = 'rmp' and f.name = 'Core platform'
   and not exists (select 1 from console.invoice_lines il where il.feature_id = f.id);
update console.app_features set price_year = price_month * 10 where product_code = 'rmp' and price_year = 0;
select console.sync_app_price('rmp');

-- ---------- tables ----------
create table if not exists console.rmp_bom (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  part_code text not null, material_code text not null,
  rm_kg numeric check (rm_kg is null or rm_kg >= 0),            -- raw material per piece before loss; blank = the part's weight from the Operations Master
  loss_pct numeric not null default 0 check (loss_pct >= 0 and loss_pct < 100),   -- bar end, parting, chips, forging flash — on top of rm_kg
  notes text, sample boolean not null default false, updated_by text, updated_at timestamptz not null default now(),
  unique (customer_id, part_code, material_code));
create table if not exists console.rmp_stock (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  material_code text not null,
  on_hand_kg numeric not null default 0 check (on_hand_kg >= 0), safety_kg numeric not null default 0 check (safety_kg >= 0),
  lead_days int check (lead_days is null or lead_days >= 0), moq_kg numeric check (moq_kg is null or moq_kg >= 0), pack_kg numeric check (pack_kg is null or pack_kg >= 0),
  sample boolean not null default false, updated_by text, updated_at timestamptz not null default now(),
  unique (customer_id, material_code));
create table if not exists console.rmp_demand (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'), part_code text not null,
  start_qty numeric not null check (start_qty >= 0), sales_qty numeric, need_by date,
  source text not null default 'capacity' check (source in ('capacity', 'manual')),       -- manual wins: a published plan never overwrites a typed quantity
  sample boolean not null default false, published_by text, published_at timestamptz not null default now(),
  unique (customer_id, month, part_code));
create table if not exists console.rmp_orders (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  material_code text not null, supplier_code text, month text, po_no text,
  qty_kg numeric not null check (qty_kg > 0), rate numeric, order_date date, due_date date,
  status text not null default 'planned' check (status in ('planned', 'ordered', 'received', 'cancelled')),
  received_kg numeric, received_on date, notes text,
  sample boolean not null default false, updated_by text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists console.rmp_settings (      -- allowances used to work out the raw material from the drawing: one row per company
  customer_id uuid primary key references console.customers(id) on delete cascade, data jsonb not null default '{}',
  updated_by text, updated_at timestamptz not null default now());
create index if not exists rmp_orders_customer on console.rmp_orders (customer_id, status, material_code);
create index if not exists rmp_demand_month on console.rmp_demand (customer_id, month);
do $$ declare t text; begin foreach t in array array['rmp_bom','rmp_stock','rmp_demand','rmp_orders','rmp_settings'] loop
  execute format('alter table console.%I enable row level security', t);
  execute format('drop policy if exists %I on console.%I', t || '_staff', t);
  execute format('create policy %I on console.%I for all to authenticated using (console.is_staff()) with check (console.is_staff())', t || '_staff', t);
end loop; end $$;

-- ---------- access: same roles as APQP / PPAP (Administration › Users & access) ----------
create or replace function public.kmr_rmp_context(p_slug text) returns jsonb language sql stable security definer set search_path = console, public as $$
  select case when console.qp_role(c.id, 'rmp') is null then null else jsonb_build_object('role', console.qp_role(c.id, 'rmp'), 'company', c.name) end
    from console.customers c where c.slug = lower(p_slug) $$;
grant execute on function public.kmr_rmp_context(text) to authenticated;

-- everything the screens need for one month, in one call
create or replace function public.kmr_rmp_load(p_slug text, p_month text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.qp_cid(p_slug, 'rmp'); cap boolean; borg uuid; dr jsonb := '[]';
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then raise exception 'Month must look like 2026-10.'; end if;
  cap := exists (select 1 from console.licences where customer_id = cid and product_code = 'capacity' and product_ref is not null);
  -- the ballooned drawing of each part (Balloon Inspector): largest diameter and longest linear dimension, to work the blank out from
  borg := console.grand_ref(cid, 'balloon');
  if borg is not null and to_regclass('public.bi_reports') is not null then
    select coalesce(jsonb_agg(jsonb_build_object('part_code', q.part_no, 'rev', q.rev, 'od', q.od, 'len', q.len, 'items', q.n, 'updated', q.updated_at) order by q.part_no), '[]') into dr
      from (select distinct on (b.part_no) b.part_no, b.rev, b.updated_at, x.od, x.len, x.n
              from public.bi_reports b
              cross join lateral (select max((i ->> 'nominal')::numeric) filter (where i ->> 'type' = 'Diameter') od, max((i ->> 'nominal')::numeric) filter (where i ->> 'type' = 'Linear') len, count(*) n
                                    from jsonb_array_elements(case when jsonb_typeof(b.data -> 'items') = 'array' then b.data -> 'items' else '[]'::jsonb end) i
                                   where coalesce(i ->> 'nominal', '') ~ '^[0-9]+(\.[0-9]+)?$') x
             where b.org_id = borg and coalesce(b.part_no, '') <> '' order by b.part_no, b.updated_at desc) q;
  end if;
  return jsonb_build_object(
    'bom_master', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name, 'data', r.data) order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'bom' and r.active), '[]'),
    'drawings', dr, 'settings', coalesce((select data from console.rmp_settings where customer_id = cid), '{}'),
    'parts', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'parts' and r.active), '[]'),
    'materials', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'raw_materials' and r.active), '[]'),
    'suppliers', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'suppliers' and r.active), '[]'),
    'bom', coalesce((select jsonb_agg(to_jsonb(b) - 'customer_id' order by b.part_code, b.material_code) from console.rmp_bom b where b.customer_id = cid), '[]'),
    'stock', coalesce((select jsonb_agg(to_jsonb(s) - 'customer_id' order by s.material_code) from console.rmp_stock s where s.customer_id = cid), '[]'),
    'demand', coalesce((select jsonb_agg(to_jsonb(d) - 'customer_id' order by d.part_code) from console.rmp_demand d where d.customer_id = cid and d.month = p_month), '[]'),
    'months', coalesce((select jsonb_agg(m order by m desc) from (select distinct month m from console.rmp_demand where customer_id = cid) x), '[]'),
    'orders', coalesce((select jsonb_agg(to_jsonb(o) - 'customer_id' order by o.created_at desc) from console.rmp_orders o
                         where o.customer_id = cid and (o.status in ('planned', 'ordered') or o.updated_at > now() - interval '120 days')), '[]'),
    'capacity', cap,
    'today', (now() at time zone 'Asia/Kolkata')::date);
end $$;
grant execute on function public.kmr_rmp_load(text, text) to authenticated;

create or replace function public.kmr_rmp_settings_save(p_slug text, p jsonb) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); k text; clean jsonb := '{}';
begin
  for k in select unnest(array['density', 'face_mm', 'part_mm', 'remnant_mm', 'forge_pct', 'cast_yield_pct']) loop
    if coalesce(p ->> k, '') ~ '^[0-9]+(\.[0-9]+)?$' then clean := clean || jsonb_build_object(k, (p ->> k)::numeric); end if;
  end loop;
  insert into console.rmp_settings (customer_id, data, updated_by) values (cid, clean, lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (customer_id) do update set data = excluded.data, updated_at = now(), updated_by = excluded.updated_by;
end $$;

-- ---------- review and approval: the figure moves to the Operations Master (bill of material list; the part's material) ----------
create or replace function public.kmr_rmp_approve(p_slug text, p_rows jsonb) returns integer
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); r jsonb; n int := 0; me text := lower(coalesce(auth.jwt() ->> 'email', '')); pc text; mc text; kg numeric; pname text; prev jsonb; rev int;
        today text := to_char((now() at time zone 'Asia/Kolkata')::date, 'YYYY-MM-DD');
begin
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    pc := trim(coalesce(r ->> 'part_code', '')); mc := trim(coalesce(r ->> 'material_code', ''));
    select name into pname from console.ops_records where customer_id = cid and kind = 'parts' and code = pc;
    if not found then raise exception 'Part % is not in Operations Master › Parts.', pc; end if;
    if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
    kg := nullif(r ->> 'kg', '')::numeric;
    if kg is null or kg <= 0 then raise exception 'Enter the kg per part for %.', pc; end if;
    select data into prev from console.ops_records where customer_id = cid and kind = 'bom' and code = pc || '/' || mc;
    rev := coalesce(nullif(prev ->> 'revision', '')::int, 0) + 1;
    insert into console.ops_records (customer_id, kind, code, name, data, active, updated_by)
    values (cid, 'bom', pc || '/' || mc, coalesce(pname, ''), jsonb_strip_nulls(jsonb_build_object('part_no', pc, 'material', mc, 'form', nullif(r ->> 'form', ''), 'size', nullif(r ->> 'size', ''),
              'blank_kg', round(kg, 4), 'calc_kg', nullif(r ->> 'calc_kg', '')::numeric, 'finished_kg', nullif(r ->> 'finished_kg', '')::numeric, 'cut_mm', nullif(r ->> 'cut_mm', '')::numeric,
              'pcs_per_bar', nullif(r ->> 'pcs_per_bar', '')::numeric, 'drawing_rev', nullif(r ->> 'drawing_rev', ''), 'basis', nullif(left(r ->> 'basis', 400), ''),
              'status', 'Approved', 'revision', rev::text, 'approved_by', me, 'approved_on', today)), true, me)
    on conflict (customer_id, kind, code) do update set name = excluded.name, data = excluded.data, active = true, updated_at = now(), updated_by = me;
    update console.ops_records set data = data || jsonb_build_object('material', mc), updated_at = now(), updated_by = me
     where customer_id = cid and kind = 'parts' and code = pc and (coalesce(data ->> 'material', '') = '' or coalesce(r ->> 'set_part_material', '') = 'true');
    n := n + 1;
  end loop;
  return n;
end $$;
create or replace function public.kmr_rmp_unapprove(p_slug text, p_part text, p_material text) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin delete from console.ops_records where customer_id = cid and kind = 'bom' and code = trim(p_part) || '/' || trim(p_material); end $$;

-- ---------- bill of material ----------
create or replace function public.kmr_rmp_bom_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid; pc text := trim(coalesce(p ->> 'part_code', '')); mc text := trim(coalesce(p ->> 'material_code', ''));
begin
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'parts' and code = pc) then raise exception 'Part % is not in Operations Master › Parts.', pc; end if;
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  insert into console.rmp_bom (customer_id, part_code, material_code, rm_kg, loss_pct, notes, updated_by)
  values (cid, pc, mc, nullif(p ->> 'rm_kg', '')::numeric, coalesce(nullif(p ->> 'loss_pct', '')::numeric, 0), nullif(p ->> 'notes', ''), lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (customer_id, part_code, material_code) do update set rm_kg = excluded.rm_kg, loss_pct = excluded.loss_pct, notes = excluded.notes, updated_by = excluded.updated_by, updated_at = now(), sample = false
  returning id into rid;
  return rid;
end $$;
create or replace function public.kmr_rmp_bom_delete(p_slug text, p_id uuid) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin delete from console.rmp_bom where id = p_id and customer_id = cid; end $$;
grant execute on function public.kmr_rmp_bom_save(text, jsonb), public.kmr_rmp_bom_delete(text, uuid) to authenticated;

-- ---------- stock and planning data per material ----------
create or replace function public.kmr_rmp_stock_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid; mc text := trim(coalesce(p ->> 'material_code', ''));
begin
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  insert into console.rmp_stock (customer_id, material_code, on_hand_kg, safety_kg, lead_days, moq_kg, pack_kg, updated_by)
  values (cid, mc, coalesce(nullif(p ->> 'on_hand_kg', '')::numeric, 0), coalesce(nullif(p ->> 'safety_kg', '')::numeric, 0), nullif(p ->> 'lead_days', '')::int,
          nullif(p ->> 'moq_kg', '')::numeric, nullif(p ->> 'pack_kg', '')::numeric, lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (customer_id, material_code) do update set
    on_hand_kg = case when p ? 'on_hand_kg' then excluded.on_hand_kg else console.rmp_stock.on_hand_kg end,
    safety_kg = case when p ? 'safety_kg' then excluded.safety_kg else console.rmp_stock.safety_kg end,
    lead_days = case when p ? 'lead_days' then excluded.lead_days else console.rmp_stock.lead_days end,
    moq_kg = case when p ? 'moq_kg' then excluded.moq_kg else console.rmp_stock.moq_kg end,
    pack_kg = case when p ? 'pack_kg' then excluded.pack_kg else console.rmp_stock.pack_kg end,
    updated_by = excluded.updated_by, updated_at = now(), sample = false
  returning id into rid;
  return rid;
end $$;
grant execute on function public.kmr_rmp_stock_save(text, jsonb) to authenticated;

-- ---------- parts to start: typed by hand (a typed quantity is never overwritten by the Capacity Planner) ----------
create or replace function public.kmr_rmp_demand_save(p_slug text, p_month text, p_rows jsonb) returns integer
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); r jsonb; n int := 0;
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then raise exception 'Month must look like 2026-10.'; end if;
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'parts' and code = trim(coalesce(r ->> 'part_code', ''))) then
      raise exception 'Part % is not in Operations Master › Parts.', r ->> 'part_code';
    end if;
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, need_by, source, published_by)
    values (cid, p_month, trim(r ->> 'part_code'), greatest(0, coalesce(nullif(r ->> 'start_qty', '')::numeric, 0)), nullif(r ->> 'need_by', '')::date, 'manual', lower(coalesce(auth.jwt() ->> 'email', '')))
    on conflict (customer_id, month, part_code) do update set start_qty = excluded.start_qty, need_by = excluded.need_by, source = 'manual', published_by = excluded.published_by, published_at = now(), sample = false;
    n := n + 1;
  end loop;
  return n;
end $$;
-- hand the part back to the Capacity Planner (the typed quantity is removed; the next save of the plan publishes it again)
create or replace function public.kmr_rmp_demand_clear(p_slug text, p_month text, p_part text) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin delete from console.rmp_demand where customer_id = cid and month = p_month and part_code = p_part; end $$;
grant execute on function public.kmr_rmp_demand_save(text, text, jsonb), public.kmr_rmp_demand_clear(text, text, text) to authenticated;

-- ---------- the Capacity Planner publishes its parts to start (called after every save of the plan; silent when the company has no Raw Material Planning) ----------
create or replace function public.kmr_rmp_publish(p_org uuid, p_month text, p_rows jsonb) returns integer
language plpgsql security definer set search_path = console, public as $$
declare cid uuid; r jsonb; n int := 0; me text := lower(coalesce(auth.jwt() ->> 'email', '')); keep text[] := '{}';
begin
  if p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then return 0; end if;
  select l.customer_id into cid from console.licences l where l.product_code = 'capacity' and l.product_ref = p_org limit 1;
  if cid is null or not exists (select 1 from console.licences where customer_id = cid and product_code = 'rmp') then return 0; end if;
  if not coalesce((select ok from console.access_state('rmp', cid)), false) then return 0; end if;
  if coalesce(public.cp_my_role(p_org), '') not in ('admin', 'editor') then return 0; end if;
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    continue when coalesce(r ->> 'part_code', '') = '';
    keep := keep || (r ->> 'part_code');
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, sales_qty, need_by, source, published_by)
    values (cid, p_month, r ->> 'part_code', greatest(0, coalesce(nullif(r ->> 'start_qty', '')::numeric, 0)), nullif(r ->> 'sales_qty', '')::numeric, nullif(r ->> 'need_by', '')::date, 'capacity', me)
    on conflict (customer_id, month, part_code) do update set start_qty = excluded.start_qty, sales_qty = excluded.sales_qty, need_by = excluded.need_by, published_by = excluded.published_by, published_at = now(), sample = false
      where console.rmp_demand.source = 'capacity';
    n := n + 1;
  end loop;
  delete from console.rmp_demand where customer_id = cid and month = p_month and source = 'capacity' and not (part_code = any (keep));   -- parts that left the plan
  return n;
end $$;
grant execute on function public.kmr_rmp_publish(uuid, text, jsonb) to authenticated;

-- ---------- orders ----------
create or replace function public.kmr_rmp_order_save(p_slug text, p jsonb) returns uuid
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); rid uuid := nullif(p ->> 'id', '')::uuid; mc text := trim(coalesce(p ->> 'material_code', '')); st text;
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'raw_materials' and code = mc) then raise exception 'Material % is not in Operations Master › Raw material.', mc; end if;
  if coalesce(nullif(p ->> 'qty_kg', '')::numeric, 0) <= 0 then raise exception 'Enter the quantity in kg.'; end if;
  if rid is null then
    insert into console.rmp_orders (customer_id, material_code, supplier_code, month, po_no, qty_kg, rate, order_date, due_date, status, notes, updated_by)
    values (cid, mc, nullif(p ->> 'supplier_code', ''), nullif(p ->> 'month', ''), nullif(p ->> 'po_no', ''), (p ->> 'qty_kg')::numeric, nullif(p ->> 'rate', '')::numeric,
            nullif(p ->> 'order_date', '')::date, nullif(p ->> 'due_date', '')::date, case when p ->> 'status' = 'ordered' then 'ordered' else 'planned' end, nullif(p ->> 'notes', ''), lower(coalesce(auth.jwt() ->> 'email', '')))
    returning id into rid;
  else
    select status into st from console.rmp_orders where id = rid and customer_id = cid;
    if st is null then raise exception 'Unknown order.'; end if;
    if st in ('received', 'cancelled') then raise exception 'A % order cannot be changed.', st; end if;
    update console.rmp_orders set supplier_code = nullif(p ->> 'supplier_code', ''), po_no = nullif(p ->> 'po_no', ''), qty_kg = (p ->> 'qty_kg')::numeric, rate = nullif(p ->> 'rate', '')::numeric,
           order_date = nullif(p ->> 'order_date', '')::date, due_date = nullif(p ->> 'due_date', '')::date, notes = nullif(p ->> 'notes', ''),
           updated_by = lower(coalesce(auth.jwt() ->> 'email', '')), updated_at = now(), sample = false
     where id = rid and customer_id = cid;
  end if;
  return rid;
end $$;
-- planned → ordered → received (the received kg is added to the stock) · or cancelled
create or replace function public.kmr_rmp_order_status(p_slug text, p_id uuid, p_status text, p_received_kg numeric default null) returns text
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp'); o console.rmp_orders%rowtype; today date := (now() at time zone 'Asia/Kolkata')::date; kg numeric;
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  select * into o from console.rmp_orders where id = p_id and customer_id = cid for update;
  if o.id is null then raise exception 'Unknown order.'; end if;
  if p_status not in ('ordered', 'received', 'cancelled') then raise exception 'Unknown status.'; end if;
  if o.status in ('received', 'cancelled') then raise exception 'This order is already %.', o.status; end if;
  if p_status = 'ordered' then
    update console.rmp_orders set status = 'ordered', order_date = coalesce(order_date, today), updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
  elsif p_status = 'cancelled' then
    update console.rmp_orders set status = 'cancelled', updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
  else
    kg := coalesce(p_received_kg, o.qty_kg);
    if kg <= 0 then raise exception 'Enter the quantity received.'; end if;
    update console.rmp_orders set status = 'received', received_kg = kg, received_on = today, updated_at = now(), updated_by = lower(coalesce(auth.jwt() ->> 'email', '')) where id = p_id;
    insert into console.rmp_stock (customer_id, material_code, on_hand_kg, updated_by) values (cid, o.material_code, kg, lower(coalesce(auth.jwt() ->> 'email', '')))
    on conflict (customer_id, material_code) do update set on_hand_kg = console.rmp_stock.on_hand_kg + kg, updated_at = now(), updated_by = excluded.updated_by;
  end if;
  return p_status;
end $$;
create or replace function public.kmr_rmp_order_delete(p_slug text, p_id uuid) returns void
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'rmp');
begin
  perform console.require_feature(p_slug, 'rmp', 'rmp.supplier-orders-receipts');
  delete from console.rmp_orders where id = p_id and customer_id = cid and status = 'planned';
end $$;
grant execute on function public.kmr_rmp_order_save(text, jsonb), public.kmr_rmp_order_status(text, uuid, text, numeric), public.kmr_rmp_order_delete(text, uuid) to authenticated;

-- ---------- sample data: built from the Operations Master sample parts and raw materials ----------
create or replace function console.rmp_sample(p_cid uuid, p_action text) returns integer language plpgsql security definer set search_path = console, public as $$
declare today date := (now() at time zone 'Asia/Kolkata')::date; mth text := to_char((now() at time zone 'Asia/Kolkata')::date, 'YYYY-MM'); n int := 0; k int := 0; p record; m record;
begin
  if p_action = 'flush' then
    delete from console.rmp_orders where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_demand where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_bom where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.rmp_stock where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    return n;
  end if;
  if exists (select 1 from console.rmp_stock where customer_id = p_cid and sample) then return 0; end if;
  -- stock, safety stock, lead time, MOQ and pack for every sample raw material
  for m in select r.code, r.data, row_number() over (order by r.code) rn from console.ops_records r where r.customer_id = p_cid and r.kind = 'raw_materials' and r.sample and r.active loop
    insert into console.rmp_stock (customer_id, material_code, on_hand_kg, safety_kg, lead_days, moq_kg, pack_kg, sample, updated_by)
    values (p_cid, m.code, (array[2400, 5200, 900, 3100, 1800, 4200, 2600])[1 + (m.rn - 1) % 7], (array[800, 1500, 400, 1000, 600, 1200, 900])[1 + (m.rn - 1) % 7],
            case m.data ->> 'form' when 'Bar' then 10 when 'Forging' then 21 else 28 end, case m.data ->> 'form' when 'Bar' then 1000 else 2000 end, case m.data ->> 'form' when 'Bar' then 250 else 500 end, true, 'sample');
    n := n + 1;
  end loop;
  -- parts to start this month (as the Capacity Planner would publish them) and a bill of material with a loss % on the bar parts
  for p in select r.code, r.data, row_number() over (order by r.code) rn from console.ops_records r where r.customer_id = p_cid and r.kind = 'parts' and r.sample and r.active loop
    insert into console.rmp_demand (customer_id, month, part_code, start_qty, sales_qty, need_by, source, sample, published_by)
    values (p_cid, mth, p.code, round((coalesce((p.data ->> 'annual_volume')::numeric, 12000) / 12) * (0.9 + (p.rn % 4) * 0.08) / 10) * 10,
            round(coalesce((p.data ->> 'annual_volume')::numeric, 12000) / 12 / 10) * 10, today + (3 + (p.rn * 2) % 21)::int, 'capacity', true, 'sample');
    n := n + 1;
    if p.rn % 3 = 0 and p.data ->> 'material' is not null then
      insert into console.rmp_bom (customer_id, part_code, material_code, rm_kg, loss_pct, notes, sample, updated_by)
      values (p_cid, p.code, p.data ->> 'material', null, 4, 'Bar end and parting loss', true, 'sample') on conflict do nothing;
      n := n + 1;
    end if;
  end loop;
  -- two orders placed, one received
  insert into console.rmp_orders (customer_id, material_code, supplier_code, month, po_no, qty_kg, rate, order_date, due_date, status, received_kg, received_on, sample, updated_by)
  select p_cid, r.code, r.data ->> 'supplier', mth, 'PO-' || to_char(today, 'YY') || '-' || lpad((100 + o.k)::text, 4, '0'), o.qty, nullif(r.data ->> 'rate_per_kg', '')::numeric, today - o.ago, today - o.ago + 14, o.st,
         case when o.st = 'received' then o.qty end, case when o.st = 'received' then today - 2 end, true, 'sample'
    from (values (1, 'RM-EN8-65', 3000, 12, 'ordered'), (2, 'RM-EN353-F', 2000, 9, 'ordered'), (3, 'RM-EN19-45', 1000, 20, 'received')) o(k, code, qty, ago, st)
    join console.ops_records r on r.customer_id = p_cid and r.kind = 'raw_materials' and r.code = o.code and r.sample;
  get diagnostics k = row_count; n := n + k;
  return n;
end $$;
revoke all on function console.rmp_sample(uuid, text) from public, anon, authenticated;

-- ---------- portal, access, Data Master and Grand Master: every function re-created from its latest version with Raw Material Planning added ----------
create or replace function console.data_target(p_slug text, p_app text, out cid uuid, out ref uuid)
language plpgsql stable security definer set search_path = console, public as $$
begin
  select c.id into cid from console.customers c where c.slug = lower(p_slug);
  if cid is null or not console.is_customer_admin(cid) then raise exception 'Only your company administrator can manage app data.'; end if;
  if p_app = 'ops' then ref := cid; return; end if;
  if p_app in ('sales','calib','apqp','ppap','rmp') then
    if not console.has_app(cid, p_app) then raise exception 'Your company does not have this app yet.'; end if;
    ref := cid; return;
  end if;
  if p_app not in ('hrm','balloon','pd','capacity') then raise exception 'Unknown app %', p_app; end if;
  select l.product_ref into ref from console.licences l where l.customer_id = cid and l.product_code = p_app and l.product_ref is not null limit 1;
  if ref is null then raise exception 'Your company does not have this app yet.'; end if;
end $$;
revoke all on function console.data_target(text, text) from public, anon, authenticated;

create or replace function console.app2_tables(p_app text) returns text[] language sql immutable as $$
  select case p_app when 'sales' then array['sf_lines','sf_despatch','sf_actions']
                    when 'calib' then array['cal_instruments','cal_records','cal_events','cal_oot','cal_msa']
                    when 'apqp'  then array['apqp_projects','apqp_items']
                    when 'ppap'  then array['ppap_submissions']
                    when 'rmp'   then array['rmp_bom','rmp_stock','rmp_demand','rmp_orders'] end
$$;


create or replace function console.app2_export(p_app text, p_cid uuid, p_real_only boolean) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare t text; rows jsonb; tabs jsonb := '{}'; parent text;
begin
  foreach t in array console.app2_tables(p_app) loop
    parent := case when t in ('sf_lines','sf_actions','cal_instruments','apqp_projects','ppap_submissions','rmp_bom','rmp_stock','rmp_demand','rmp_orders') then null when p_app = 'sales' then 'sf_lines' when p_app = 'calib' then 'cal_instruments' else 'apqp_projects' end;
    if not p_real_only then
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x where x.customer_id = $1', t) into rows using p_cid;
    elsif parent is null then
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x where x.customer_id = $1 and not x.sample', t) into rows using p_cid;
    else
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x join console.%I p on p.id = x.%I where x.customer_id = $1 and not p.sample',
                     t, parent, case parent when 'sf_lines' then 'line_id' when 'apqp_projects' then 'project_id' else 'instrument_id' end) into rows using p_cid;
    end if;
    tabs := tabs || jsonb_build_object(t, rows);
  end loop;
  return tabs;
end $$;
revoke all on function console.app2_export(text, uuid, boolean), console.app2_clear(text, uuid, boolean), console.app2_restore(text, uuid, jsonb, boolean) from public, anon, authenticated;

create or replace function console.app2_clear(p_app text, p_cid uuid, p_real_only boolean) returns bigint
language plpgsql security definer set search_path = console, public as $$
declare n bigint := 0; k bigint;
begin
  if p_app = 'sales' then
    delete from console.sf_actions where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.sf_lines where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
  elsif p_app = 'calib' then
    delete from console.cal_instruments where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'apqp' then
    delete from console.apqp_projects where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'ppap' then
    delete from console.ppap_submissions where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'rmp' then
    delete from console.rmp_orders where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_demand where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_bom where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_stock where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
  end if;
  return n;
end $$;


create or replace function console.app2_restore(p_app text, p_cid uuid, p_tables jsonb, p_real_only boolean) returns bigint
language plpgsql security definer set search_path = console, public as $$
declare t text; rows jsonb; tot bigint := 0; k bigint;
begin
  perform console.app2_clear(p_app, p_cid, p_real_only);
  foreach t in array console.app2_tables(p_app) loop
    -- every row goes back into THIS company, whatever the file says; restored real data is never marked sample
    rows := (select coalesce(jsonb_agg(r || jsonb_build_object('customer_id', p_cid)
                       || case when t in ('sf_lines','sf_actions','cal_instruments','apqp_projects','ppap_submissions','rmp_bom','rmp_stock','rmp_demand','rmp_orders') and p_real_only then '{"sample":false}'::jsonb else '{}'::jsonb end), '[]')
               from jsonb_array_elements(coalesce(p_tables -> t, '[]')) r);
    execute format('insert into console.%I select * from jsonb_populate_recordset(null::console.%I, $1) on conflict do nothing', t, t) using rows;
    get diagnostics k = row_count; tot := tot + k;
  end loop;
  return tot;
end $$;


create or replace function public.kmr_qp_context(p_slug text, p_code text) returns jsonb language sql stable security definer set search_path = console, public as $$
  select case when console.qp_role(c.id, p_code) is null then null else jsonb_build_object('role', console.qp_role(c.id, p_code), 'company', c.name) end
    from console.customers c where c.slug = lower(p_slug) and p_code in ('apqp', 'ppap', 'rmp') $$;


create or replace function public.kmr_portal(p_slug text)
returns table (product_code text, product_name text, app_path text, purchased boolean, ok boolean, status text,
               valid_until date, message text, customer_name text, logo_url text, product_slug text,
               has_access boolean, is_contact boolean)
language plpgsql stable security definer set search_path = console, public as $$
declare
  em text := lower(coalesce(auth.jwt() ->> 'email', ''));
  uid uuid := auth.uid();
  c console.customers%rowtype;
  member boolean := false;
begin
  select * into c from console.customers where slug = lower(p_slug);
  if c.id is null or em = '' then return; end if;
  select true into member from console.licences l
   where l.customer_id = c.id and (
         (l.product_code = 'balloon'  and exists (select 1 from public.bi_members m where m.org_id = l.product_ref and lower(m.email) = em))
      or (l.product_code = 'pd'       and exists (select 1 from public.pd_members m where m.org_id = l.product_ref and lower(m.email) = em))
      or (l.product_code = 'capacity' and exists (select 1 from public.cp_members m where m.org_id = l.product_ref and m.email = em))
      or (l.product_code = 'sales'    and console.sf_member(l.customer_id, em))
      or (l.product_code = 'calib'    and console.cal_member(l.customer_id, em))
      or (l.product_code in ('apqp', 'ppap', 'rmp') and console.qp_member(l.customer_id, em, l.product_code))
      or (l.product_code = 'hrm'      and exists (select 1 from hrm.app_users u where u.tenant_id = l.product_ref and u.id = uid and u.active)))
   limit 1;
  if not coalesce(member, false) and lower(coalesce(c.contact_email, '')) <> em then return; end if;
  return query
    select p.code, p.name, p.app_path, (l.id is not null), coalesce(a.ok, false), coalesce(a.status, 'not_purchased'),
           l.valid_until, a.message, c.name, c.logo_url, l.product_slug,
           case p.code
             when 'balloon'  then exists (select 1 from public.bi_members m where m.org_id = l.product_ref and lower(m.email) = em)
             when 'pd'       then exists (select 1 from public.pd_members m where m.org_id = l.product_ref and lower(m.email) = em)
             when 'capacity' then exists (select 1 from public.cp_members m where m.org_id = l.product_ref and m.email = em)
             when 'sales'    then console.sf_member(l.customer_id, em)
             when 'calib'    then console.cal_member(l.customer_id, em)
             when 'apqp'     then console.qp_member(l.customer_id, em, 'apqp')
             when 'ppap'     then console.qp_member(l.customer_id, em, 'ppap')
             when 'rmp'      then console.qp_member(l.customer_id, em, 'rmp')
             when 'hrm'      then exists (select 1 from hrm.app_users u where u.tenant_id = l.product_ref and u.id = uid and u.active)
             else false end,
           lower(coalesce(c.contact_email, '')) = em
      from console.products p
      left join console.licences l on l.product_code = p.code and l.customer_id = c.id
      left join lateral console.access_state(p.code, l.product_ref) a on l.id is not null
     where p.active
     order by p.sort_order;
end $$;
revoke all on function public.kmr_portal(text) from public, anon;
grant execute on function public.kmr_portal(text) to authenticated;

create or replace function public.kmr_portal_join(p_slug text, p_product text) returns text
language plpgsql security definer set search_path = console, public as $$
declare em text := lower(coalesce(auth.jwt() ->> 'email', '')); cid uuid; ok boolean;
begin
  select id into cid from console.customers where slug = lower(p_slug);
  if cid is null or em = '' then raise exception 'Unknown company link.'; end if;
  if not exists (select 1 from console.licences where customer_id = cid and product_code = p_product and product_ref is not null) then
    raise exception 'This app is not set up for your company yet. Please contact KMR.';
  end if;
  if console.is_customer_admin(cid) then
    perform console.grant_admins(cid);          -- administrators: admin in every bought tool
  end if;
  perform console.sync_member(cid, em);         -- everyone: whatever Administration › Users & access says
  ok := case p_product
    when 'balloon'  then exists (select 1 from public.bi_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'balloon' where l.customer_id = cid and lower(m.email) = em)
    when 'pd'       then exists (select 1 from public.pd_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'pd' where l.customer_id = cid and lower(m.email) = em)
    when 'capacity' then exists (select 1 from public.cp_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'capacity' where l.customer_id = cid and m.email = em)
    when 'sales'    then console.sf_member(cid, em)
    when 'calib'    then console.cal_member(cid, em)
    when 'apqp'     then console.qp_member(cid, em, 'apqp')
    when 'ppap'     then console.qp_member(cid, em, 'ppap')
    when 'rmp'      then console.qp_member(cid, em, 'rmp')
    when 'hrm'      then exists (select 1 from hrm.app_users u join console.licences l on l.product_ref = u.tenant_id and l.product_code = 'hrm' where l.customer_id = cid and u.id = auth.uid() and u.active)
    else false end;
  if not ok then
    raise exception 'You have not been given access to this app. Your company administrator can add it under KMR Apps › Administration › Users & access.';
  end if;
  return 'ok';
end $$;
revoke all on function public.kmr_portal_join(text, text) from public, anon;
grant execute on function public.kmr_portal_join(text, text) to authenticated;

create or replace function public.kmr_portal_stats(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare c uuid; out jsonb := '{}'; ref uuid; today date := (now() at time zone 'Asia/Kolkata')::date;
begin
  if not exists (select 1 from public.kmr_portal(p_slug)) then return out; end if;
  select id into c from console.customers where slug = lower(p_slug);
  select product_ref into ref from console.licences where customer_id = c and product_code = 'hrm';
  if ref is not null then
    out := out || jsonb_build_object('hrm', jsonb_build_object(
      'Employees', (select count(*) from hrm.employees where tenant_id = ref and status = 'active'),
      'In today', (select count(*) from hrm.attendance_days where tenant_id = ref and work_date = today and status in ('present','half_day','missed_punch')),
      'Awaiting approval', (select count(*) from hrm.leave_requests where tenant_id = ref and status = 'pending')
                          + (select count(*) from hrm.regularisation_requests where tenant_id = ref and status = 'pending')));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'balloon';
  if ref is not null then
    out := out || jsonb_build_object('balloon', jsonb_build_object(
      'Reports', (select count(*) from public.bi_reports where org_id = ref),
      'Users', (select count(*) from public.bi_members where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'pd';
  if ref is not null then
    out := out || jsonb_build_object('pd', jsonb_build_object(
      'Projects', (select count(*) from public.pd_projects where org_id = ref),
      'Users', (select count(*) from public.pd_members where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'capacity';
  if ref is not null then
    out := out || jsonb_build_object('capacity', jsonb_build_object(
      'Users', (select count(*) from public.cp_members where org_id = ref),
      'Saved versions', (select count(*) from public.cp_history where org_id = ref) + (select count(*) from public.cp_plans where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'sales';
  if ref is not null then
    out := out || jsonb_build_object('sales', jsonb_build_object(
      'Users', (select count(*) from console.customer_members m where m.customer_id = c and coalesce(m.roles ->> 'sales', '') <> ''),
      'Parts planned', (select count(*) from console.sf_lines where customer_id = c and month = date_trunc('month', today)::date)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'calib';
  if ref is not null then
    out := out || jsonb_build_object('calib', jsonb_build_object(
      'Instruments', (select count(*) from console.cal_instruments where customer_id = c and status = 'In use'),
      'Overdue', (select count(*) from console.cal_instruments where customer_id = c and status = 'In use' and next_due < (now() at time zone 'Asia/Kolkata')::date)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'apqp';
  if ref is not null then
    out := out || jsonb_build_object('apqp', jsonb_build_object(
      'Programmes', (select count(*) from console.apqp_projects where customer_id = c and status = 'active'),
      'Open deliverables', (select count(*) from console.apqp_items i join console.apqp_projects p on p.id = i.project_id where i.customer_id = c and p.status = 'active' and i.status in ('open', 'progress')),
      'Overdue', (select count(*) from console.apqp_items i join console.apqp_projects p on p.id = i.project_id where i.customer_id = c and p.status = 'active' and i.status in ('open', 'progress') and i.due < today)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'ppap';
  if ref is not null then
    out := out || jsonb_build_object('ppap', jsonb_build_object(
      'Submissions', (select count(*) from console.ppap_submissions where customer_id = c),
      'Awaiting approval', (select count(*) from console.ppap_submissions where customer_id = c and status = 'submitted'),
      'Approved', (select count(*) from console.ppap_submissions where customer_id = c and status in ('approved', 'interim'))));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'rmp';
  if ref is not null then
    out := out || jsonb_build_object('rmp', jsonb_build_object(
      'Materials', (select count(*) from console.rmp_stock where customer_id = c),
      'Orders placed', (select count(*) from console.rmp_orders where customer_id = c and status = 'ordered'),
      'Planned orders', (select count(*) from console.rmp_orders where customer_id = c and status = 'planned')));
  end if;
  return out;
end $$;
revoke all on function public.kmr_portal_stats(text) from public, anon;
grant execute on function public.kmr_portal_stats(text) to authenticated;

create or replace function public.kmr_data_overview(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid; l record; out jsonb := '[]'::jsonb; t text; n bigint; det jsonb; tot bigint; a text;
begin
  select id into cid from console.customers where slug = lower(p_slug);
  if cid is null or not console.is_customer_admin(cid) then raise exception 'Only your company administrator can manage app data.'; end if;
  for l in select product_code, product_ref from console.licences where customer_id = cid and product_ref is not null
             and product_code in ('hrm','balloon','pd','capacity') order by array_position(array['hrm','balloon','pd','capacity'], product_code) loop
    det := '{}'; tot := 0;
    if l.product_code = 'hrm' then
      foreach t in array array['employees','attendance_days','leave_requests','payroll_runs','loans','id_cards','onboarding_invites'] loop
        if to_regclass('hrm.' || t) is null then continue; end if;
        execute format('select count(*) from hrm.%I where tenant_id = $1', t) into n using l.product_ref;
        det := det || jsonb_build_object(t, n); tot := tot + n;
      end loop;
    else
      foreach t in array console.data_tables(l.product_code) loop
        execute format('select count(*) from public.%I where org_id = $1', t) into n using l.product_ref;
        det := det || jsonb_build_object(t, n); tot := tot + n;
      end loop;
    end if;
    out := out || jsonb_build_array(jsonb_build_object('app', l.product_code, 'records', tot, 'detail', det));
  end loop;
  foreach a in array array['sales','calib','apqp','ppap','rmp'] loop
    continue when not console.has_app(cid, a);
    det := '{}'; tot := 0;
    foreach t in array console.app2_tables(a) loop
      execute format('select count(*) from console.%I where customer_id = $1', t) into n using cid;
      det := det || jsonb_build_object(t, n); tot := tot + n;
    end loop;
    out := out || jsonb_build_array(jsonb_build_object('app', a, 'records', tot, 'detail', det));
  end loop;
  select count(*) into n from console.ops_records where customer_id = cid;
  out := out || jsonb_build_array(jsonb_build_object('app', 'ops', 'records', n, 'detail', jsonb_build_object('ops_records', n)));
  return out;
end $$;
grant execute on function public.kmr_data_overview(text) to authenticated;

create or replace function public.kmr_data_export(p_slug text, p_app text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare tg record; t text; rows jsonb; tabs jsonb := '{}';
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_app = 'hrm' then
    tabs := jsonb_build_object('hrm', hrm.company_export(tg.ref));
  elsif p_app = 'ops' then
    select coalesce(jsonb_agg(to_jsonb(r) - 'customer_id' order by r.kind, r.code), '[]') into rows from console.ops_records r where r.customer_id = tg.cid;
    tabs := jsonb_build_object('ops_records', rows);
  elsif p_app in ('sales','calib','apqp','ppap','rmp') then
    tabs := console.app2_export(p_app, tg.cid, false);
  else
    foreach t in array console.data_tables(p_app) loop
      execute format('select coalesce(jsonb_agg(to_jsonb(x)), ''[]'') from public.%I x where x.org_id = $1', t) into rows using tg.ref;
      tabs := tabs || jsonb_build_object(t, rows);
    end loop;
  end if;
  return jsonb_build_object('format', 'kmr-app-data', 'version', 1, 'app', p_app, 'company', lower(p_slug), 'exported_at', now(), 'tables', tabs);
end $$;
grant execute on function public.kmr_data_export(text, text) to authenticated;

create or replace function public.kmr_data_flush(p_slug text, p_app text, p_hrm_setup boolean default false) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare tg record;
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_app = 'hrm' then return hrm.company_flush(tg.ref, coalesce(p_hrm_setup, false)); end if;
  if p_app in ('sales','calib','apqp','ppap','rmp') then return jsonb_build_object('removed', console.app2_clear(p_app, tg.cid, false)); end if;
  return jsonb_build_object('removed', console.data_clear(p_app, tg.cid, tg.ref));
end $$;
grant execute on function public.kmr_data_flush(text, text, boolean) to authenticated;

create or replace function public.kmr_data_import(p_slug text, p_app text, p_data jsonb) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare tg record; t text; rows jsonb; n bigint; k bigint; tot bigint := 0; pass int; todo text[];
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_data ->> 'format' is distinct from 'kmr-app-data' then raise exception 'This is not a KMR Data Master file.'; end if;
  if p_data ->> 'app' is distinct from p_app then raise exception 'This file is a backup of another app (%).', p_data ->> 'app'; end if;
  if p_app = 'hrm' then
    return jsonb_build_object('restored', hrm.company_import(tg.ref, p_data -> 'tables' -> 'hrm'));
  end if;
  if p_app in ('sales','calib','apqp','ppap','rmp') then
    return jsonb_build_object('restored', console.app2_restore(p_app, tg.cid, p_data -> 'tables', false));
  end if;
  perform console.data_clear(p_app, tg.cid, tg.ref);
  if p_app = 'ops' then
    rows := (select coalesce(jsonb_agg(r || jsonb_build_object('customer_id', tg.cid)), '[]') from jsonb_array_elements(coalesce(p_data -> 'tables' -> 'ops_records', '[]')) r);
    insert into console.ops_records select * from jsonb_populate_recordset(null::console.ops_records, rows) on conflict do nothing;
    get diagnostics n = row_count;
    return jsonb_build_object('restored', n);
  end if;
  perform console.app_triggers(case p_app when 'balloon' then 'bi' when 'pd' then 'pd' else 'cp' end, false);
  todo := array(select x from unnest(console.data_tables(p_app)) x where (p_data -> 'tables') ? x);
  for pass in 1..4 loop
    exit when cardinality(todo) = 0;
    foreach t in array todo loop
      rows := (select coalesce(jsonb_agg(r || jsonb_build_object('org_id', tg.ref)), '[]') from jsonb_array_elements(p_data -> 'tables' -> t) r);
      begin
        execute format('insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1) on conflict do nothing', t, t) using rows;
        get diagnostics k = row_count; tot := tot + k; todo := array_remove(todo, t);
      exception when foreign_key_violation then null;
      end;
    end loop;
  end loop;
  perform console.app_triggers(case p_app when 'balloon' then 'bi' when 'pd' then 'pd' else 'cp' end, true);
  if cardinality(todo) > 0 then raise exception 'Could not restore: %.', array_to_string(todo, ', '); end if;
  return jsonb_build_object('restored', tot);
end $$;
grant execute on function public.kmr_data_import(text, text, jsonb) to authenticated;

create or replace function public.kmr_grand_sample(p_slug text, p_action text) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; r uuid; n int; k int; flow jsonb;
begin
  if p_action not in ('load','flush') then raise exception 'Unknown action.'; end if;
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    if p_action = 'load' then
      if exists (select 1 from hrm.employees where tenant_id = r and email like '%@demo.kmr.test') then n := 0;
      else n := hrm.demo_load(r); perform hrm.demo_payroll(r); end if;
      if to_regprocedure('hrm.demo_flow(uuid)') is not null then
        flow := hrm.demo_flow(r);
        out := out || jsonb_build_object('hrm_flow', flow);
      end if;
    else
      if exists (select 1 from information_schema.columns where table_schema = 'hrm' and table_name = 'candidates' and column_name = 'sample') then
        execute 'select count(*) from hrm.candidates where tenant_id = $1 and sample' into k using r;
        out := out || jsonb_build_object('hrm_candidates', k);
      end if;
      n := hrm.demo_flush(r);
    end if;
    out := out || jsonb_build_object('hrm', n, 'hrm_tenant', r);
  end if;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    out := out || jsonb_build_object('balloon', public.kmr_ops_sample_drawing(p_slug, p_action));
  end if;
  if p_action = 'load' then
    -- the Operations Master first: Sales Flow and Calibration Hub are built from its sample parts, rate contracts and gauges
    out := out || jsonb_build_object('ops', (public.kmr_ops_sample_load(p_slug) ->> 'added')::int);
    if console.has_app(cid, 'sales') then out := out || jsonb_build_object('sales', console.sf_sample(cid, 'load')); end if;
    if console.has_app(cid, 'calib') then out := out || jsonb_build_object('calib', console.cal_sample(cid, 'load')); end if;
    if console.has_app(cid, 'apqp') then out := out || jsonb_build_object('apqp', console.apqp_sample(cid, 'load')); end if;
    if console.has_app(cid, 'ppap') then out := out || jsonb_build_object('ppap', console.ppap_sample(cid, 'load')); end if;
    if console.has_app(cid, 'rmp') then out := out || jsonb_build_object('rmp', console.rmp_sample(cid, 'load')); end if;
  else
    if console.has_app(cid, 'sales') then out := out || jsonb_build_object('sales', console.sf_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'rmp') then out := out || jsonb_build_object('rmp', console.rmp_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'ppap') then out := out || jsonb_build_object('ppap', console.ppap_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'apqp') then out := out || jsonb_build_object('apqp', console.apqp_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'calib') then out := out || jsonb_build_object('calib', console.cal_sample(cid, 'flush')); end if;
    out := out || jsonb_build_object('ops', public.kmr_ops_sample_flush(p_slug));
  end if;
  return out;
end $$;
revoke all on function public.kmr_grand_sample(text, text) from public, anon;
grant execute on function public.kmr_grand_sample(text, text) to authenticated;

create or replace function public.kmr_grand_overview(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); r uuid; real_ jsonb := '{}'; smp jsonb := '{}'; t text; n bigint; k bigint; c console.customers%rowtype;
begin
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    select count(*) filter (where coalesce(email, '') not like '%@demo.kmr.test'), count(*) filter (where coalesce(email, '') like '%@demo.kmr.test')
      into n, k from hrm.employees where tenant_id = r;
    real_ := real_ || jsonb_build_object('hrm', n); smp := smp || jsonb_build_object('hrm', k);
    if exists (select 1 from information_schema.columns where table_schema = 'hrm' and table_name = 'candidates' and column_name = 'sample') then
      execute 'select count(*) filter (where not sample), count(*) filter (where sample) from hrm.candidates where tenant_id = $1' into n, k using r;
      real_ := real_ || jsonb_build_object('hrm_candidates', n); smp := smp || jsonb_build_object('hrm_candidates', k);
    end if;
  end if;
  r := console.grand_ref(cid, 'balloon');
  if r is not null and to_regclass('public.bi_reports') is not null then
    execute 'select count(*) filter (where coalesce(file_path, '''') not like ''static:%''), count(*) filter (where file_path like ''static:%'') from public.bi_reports where org_id = $1'
      into n, k using r;
    real_ := real_ || jsonb_build_object('balloon', n); smp := smp || jsonb_build_object('balloon', k);
  end if;
  foreach t in array array['pd','capacity'] loop
    r := console.grand_ref(cid, t);
    if r is null then continue; end if;
    n := 0;
    declare tb text; m bigint; begin
      foreach tb in array console.data_tables(t) loop
        execute format('select count(*) from public.%I where org_id = $1', tb) into m using r; n := n + m;
      end loop;
    end;
    real_ := real_ || jsonb_build_object(t, n);
  end loop;
  if console.has_app(cid, 'sales') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.sf_lines where customer_id = cid;
    real_ := real_ || jsonb_build_object('sales', n); smp := smp || jsonb_build_object('sales', k);
  end if;
  if console.has_app(cid, 'calib') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.cal_instruments where customer_id = cid;
    real_ := real_ || jsonb_build_object('calib', n); smp := smp || jsonb_build_object('calib', k);
  end if;
  if console.has_app(cid, 'apqp') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.apqp_projects where customer_id = cid;
    real_ := real_ || jsonb_build_object('apqp', n); smp := smp || jsonb_build_object('apqp', k);
  end if;
  if console.has_app(cid, 'ppap') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.ppap_submissions where customer_id = cid;
    real_ := real_ || jsonb_build_object('ppap', n); smp := smp || jsonb_build_object('ppap', k);
  end if;
  if console.has_app(cid, 'rmp') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.rmp_stock where customer_id = cid;
    real_ := real_ || jsonb_build_object('rmp', n); smp := smp || jsonb_build_object('rmp', k);
  end if;
  select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.ops_records where customer_id = cid;
  real_ := real_ || jsonb_build_object('ops', n); smp := smp || jsonb_build_object('ops', k);
  select * into c from console.customers where id = cid;
  return jsonb_build_object('real', real_, 'sample', smp, 'staff', console.is_staff(),
    'admin', jsonb_build_object(
      'company', c.name, 'logo', coalesce(c.logo_url, '') <> '',
      'details', (select count(*) from unnest(array[c.legal_name, c.tax_id, c.address, c.city, c.state, c.postal_code, c.contact_phone]) v where coalesce(v, '') <> ''),
      'users', (select count(*) from console.customer_members where customer_id = cid),
      'invoices', (select count(*) from console.invoices where customer_id = cid),
      'payments', (select count(*) from console.payments p join console.invoices i on i.id = p.invoice_id where i.customer_id = cid)));
end $$;
revoke all on function public.kmr_grand_overview(text) from public, anon;
grant execute on function public.kmr_grand_overview(text) to authenticated;

create or replace function public.kmr_grand_real_export(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); apps jsonb := '{}'; t text;
begin
  foreach t in array array['hrm','pd','capacity'] loop
    if console.grand_ref(cid, t) is not null then apps := apps || jsonb_build_object(t, public.kmr_data_export(p_slug, t)); end if;
  end loop;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    apps := apps || jsonb_build_object('balloon', public.kmr_balloon_own_export(p_slug));
  end if;
  foreach t in array array['sales','calib','apqp','ppap','rmp'] loop
    if console.has_app(cid, t) then apps := apps || jsonb_build_object(t, jsonb_build_object('format', 'kmr-app-real', 'tables', console.app2_export(t, cid, true))); end if;
  end loop;
  apps := apps || jsonb_build_object('ops', jsonb_build_object('format', 'kmr-ops-own', 'records',
    coalesce((select jsonb_agg(jsonb_build_object('kind', r.kind, 'code', r.code, 'name', r.name, 'data', r.data, 'active', r.active) order by r.kind, r.code)
                from console.ops_records r where r.customer_id = cid and not r.sample), '[]')));
  return jsonb_build_object('format', 'kmr-real-data', 'version', 1, 'company', lower(p_slug), 'exported_at', now(), 'apps', apps);
end $$;
revoke all on function public.kmr_grand_real_export(text) from public, anon;
grant execute on function public.kmr_grand_real_export(text) to authenticated;

create or replace function public.kmr_grand_real_flush(p_slug text) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; r uuid; t text; n int;
begin
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    out := out || jsonb_build_object('hrm_candidates', console.grand_hrm_real_candidates(r));
    out := out || jsonb_build_object('hrm', hrm.real_flush(r));
  end if;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    out := out || jsonb_build_object('balloon', public.kmr_balloon_own_flush(p_slug));
  end if;
  foreach t in array array['pd','capacity'] loop
    r := console.grand_ref(cid, t);
    if r is not null then out := out || jsonb_build_object(t, console.data_clear(t, cid, r)); end if;
  end loop;
  -- Sales Flow / Calibration Hub: count the parent records (plan lines, instruments) removed, sample ones stay
  if console.has_app(cid, 'sales') then
    select count(*) into n from console.sf_lines where customer_id = cid and not sample;
    perform console.app2_clear('sales', cid, true); out := out || jsonb_build_object('sales', n);
  end if;
  if console.has_app(cid, 'calib') then
    select count(*) into n from console.cal_instruments where customer_id = cid and not sample;
    perform console.app2_clear('calib', cid, true); out := out || jsonb_build_object('calib', n);
  end if;
  if console.has_app(cid, 'apqp') then
    select count(*) into n from console.apqp_projects where customer_id = cid and not sample;
    perform console.app2_clear('apqp', cid, true); out := out || jsonb_build_object('apqp', n);
  end if;
  if console.has_app(cid, 'ppap') then
    select count(*) into n from console.ppap_submissions where customer_id = cid and not sample;
    perform console.app2_clear('ppap', cid, true); out := out || jsonb_build_object('ppap', n);
  end if;
  if console.has_app(cid, 'rmp') then
    select count(*) into n from console.rmp_stock where customer_id = cid and not sample;
    perform console.app2_clear('rmp', cid, true); out := out || jsonb_build_object('rmp', n);
  end if;
  delete from console.ops_records where customer_id = cid and not sample; get diagnostics n = row_count;
  return out || jsonb_build_object('ops', n);
end $$;
revoke all on function public.kmr_grand_real_flush(text) from public, anon;
grant execute on function public.kmr_grand_real_flush(text) to authenticated;

create or replace function public.kmr_grand_real_import(p_slug text, p_data jsonb) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; t text; a jsonb; n int; me text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if p_data ->> 'format' is distinct from 'kmr-real-data' then raise exception 'This is not a Grand Master real-data file.'; end if;
  if lower(coalesce(p_data ->> 'company', '')) <> lower(p_slug) then
    raise exception 'This file is a backup of another company (%).', p_data ->> 'company';
  end if;
  foreach t in array array['hrm','pd','capacity'] loop
    a := p_data -> 'apps' -> t;
    if a is null or console.grand_ref(cid, t) is null then continue; end if;
    out := out || jsonb_build_object(t, public.kmr_data_import(p_slug, t, a) -> 'restored');
    if t = 'hrm' then
      select count(*) into n from hrm.employees where tenant_id = console.grand_ref(cid, 'hrm') and coalesce(email, '') not like '%@demo.kmr.test';
      out := out || jsonb_build_object('hrm', n, 'hrm_candidates', console.grand_hrm_real_candidates(console.grand_ref(cid, 'hrm')));
    end if;
  end loop;
  a := p_data -> 'apps' -> 'balloon';
  if a is not null and console.grand_ref(cid, 'balloon') is not null then
    perform public.kmr_balloon_own_flush(p_slug);
    if jsonb_array_length(coalesce(a -> 'tables' -> 'bi_reports', '[]')) > 0 then
      out := out || jsonb_build_object('balloon', public.kmr_balloon_own_load(p_slug, a));
    else out := out || jsonb_build_object('balloon', 0); end if;
  end if;
  -- Operations Master before Sales Flow / Calibration Hub (they point at its parts and gauges by code)
  a := p_data -> 'apps' -> 'ops';
  if a is not null then
    delete from console.ops_records where customer_id = cid and not sample;
    insert into console.ops_records (customer_id, kind, code, name, data, active, sample, updated_by)
    select cid, x ->> 'kind', x ->> 'code', coalesce(x ->> 'name', x ->> 'code'), coalesce(x -> 'data', '{}'), coalesce((x ->> 'active')::boolean, true), false, me
      from jsonb_array_elements(coalesce(a -> 'records', '[]')) x
     where coalesce(x ->> 'kind', '') <> '' and coalesce(x ->> 'code', '') <> ''
    on conflict (customer_id, kind, code) do update set name = excluded.name, data = excluded.data, active = excluded.active, sample = false, updated_by = me;
    get diagnostics n = row_count; out := out || jsonb_build_object('ops', n);
  end if;
  foreach t in array array['sales','calib','apqp','ppap','rmp'] loop
    a := p_data -> 'apps' -> t;
    if a is null or not console.has_app(cid, t) then continue; end if;
    perform console.app2_restore(t, cid, a -> 'tables', true);
    if t = 'sales' then select count(*) into n from console.sf_lines where customer_id = cid and not sample;
    elsif t = 'calib' then select count(*) into n from console.cal_instruments where customer_id = cid and not sample;
    elsif t = 'apqp' then select count(*) into n from console.apqp_projects where customer_id = cid and not sample;
    elsif t = 'ppap' then select count(*) into n from console.ppap_submissions where customer_id = cid and not sample;
    else select count(*) into n from console.rmp_stock where customer_id = cid and not sample; end if;
    out := out || jsonb_build_object(t, n);
  end loop;
  return out;
end $$;
revoke all on function public.kmr_grand_real_import(text, jsonb) from public, anon;
grant execute on function public.kmr_grand_real_import(text, jsonb) to authenticated;

-- the demo workspace switches Raw Material Planning on too
drop function if exists console.demo_refresh(uuid);
create or replace function console.demo_refresh(p_cid uuid, p_full boolean default true) returns jsonb language plpgsql security definer set search_path = console, public as $$
declare cu console.customers%rowtype; pcode text; out jsonb;
begin
  select * into cu from console.customers where id = p_cid and kind = 'demo';
  if not found then raise exception 'This is not a demo workspace.'; end if;
  foreach pcode in array array['sales', 'calib', 'apqp', 'ppap', 'rmp'] loop
    insert into console.licences (customer_id, product_code, status, valid_until, seats, notes, product_ref, product_slug)
    select p_cid, pcode, 'active', null, 25, 'KMR demo data', p_cid, cu.slug where exists (select 1 from console.products pr where pr.code = pcode)
    on conflict (customer_id, product_code) do nothing;
  end loop;
  perform set_config('request.jwt.claims', jsonb_build_object('role', 'authenticated', 'email', lower(coalesce(cu.contact_email, ''))) ::text, true);
  if p_full then perform public.kmr_grand_sample(cu.slug, 'flush'); end if;   -- the nightly reset starts clean; the first load only adds what is missing
  out := public.kmr_grand_sample(cu.slug, 'load');
  return out;
end $$;
revoke all on function console.demo_refresh(uuid, boolean), console.demo_refresh_all() from public, anon, authenticated;
grant execute on function console.demo_refresh(uuid, boolean), console.demo_refresh_all() to service_role;

-- the app's functions join the same execute grants as the other apps
do $$ declare f record; begin
  for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname ~ '^kmr_rmp_' loop
    execute format('revoke all on function %s from public, anon', f.sig);
    execute format('grant execute on function %s to authenticated', f.sig);
  end loop;
end $$;
