-- =====================================================================
-- 0059 — Maintenance (a new KMR App)
--  • Breakdown log per machine: reported → attended → restored, with root cause, corrective and preventive action, spares used (IATF 16949 8.5.1.5, ISO 9001 7.1.3).
--  • Machine downtime analysis, MTBF, MTTR, availability, repeat failures; preventive-maintenance schedule with compliance.
--  • Machine history card: master data + every breakdown, PM and modification, printable (IATF 16949 8.5.1.5 / ISO 9001 7.1.3 / 7.5.3 documented information).
--  • A closed breakdown books its downtime in MMD loss hours against the chosen D code, so the loss is typed once.
-- Needs 0058 (MMD). Safe to re-run. Generated by scripts/make-mnt.py.
-- =====================================================================
do $$ begin
  if to_regprocedure('public.kmr_mmd_load(text)') is null then raise exception 'Run 0058_mmd.sql first.'; end if;
end $$;

insert into console.products (code, name, description, app_path, seat_label, current_version, sort_order) values
  ('mnt', 'Maintenance', 'Breakdown log, downtime analysis, MTBF and MTTR, preventive maintenance plan and the machine history card', '/it/mnt.html', 'users', '1.0.0', 110)
on conflict (code) do nothing;
insert into console.releases (product_code, version, notes) values
  ('mnt', '1.0.0', 'Maintenance: breakdown log, downtime analysis, MTBF / MTTR, preventive maintenance plan, machine history card') on conflict do nothing;
insert into console.prices (product_code, period, currency, unit_amount, min_seats, active, note)
select v.code, v.period, 'INR', v.amt, 1, true, 'Starting price list (0059) — change in Console › Billing'
  from (values ('mnt', 'month', 3000), ('mnt', 'year', 30000)) v(code, period, amt)
on conflict (product_code, period, currency) do nothing;
insert into public.app_listings (code, name, tagline, features, sort_order, is_active) values
  ('mnt', 'Maintenance', 'Fewer breakdowns, faster repairs: every stoppage logged, analysed and linked to the machine history card.',
   E'Breakdown log with root cause, corrective and preventive action\nMTBF, MTTR, availability and downtime Pareto per machine\nPreventive maintenance schedule and printable machine history card for IATF 16949', 110, true)
on conflict (code) do update set name = excluded.name, tagline = coalesce(public.app_listings.tagline, excluded.tagline), features = coalesce(public.app_listings.features, excluded.features);

insert into console.app_features (product_code, name, detail, is_core, price_month, price_year, setup_fee, sort_order) values
  ('mnt', 'Breakdown log & downtime', 'Report, attend and close breakdowns with root cause, action and spares; downtime flows to MMD loss hours', true, 1200, 0, 15000, 10),
  ('mnt', 'Preventive maintenance plan', 'PM schedule per machine from the Operations Master PM frequency, due / overdue list, completion records and compliance', false, 700, 0, 8000, 20),
  ('mnt', 'MTTR, MTBF & analysis', 'MTBF, MTTR and availability per machine, downtime Pareto by machine and cause, repeat failures, monthly trend', false, 800, 0, 10000, 30),
  ('mnt', 'Machine history card', 'Printable card per machine: master data, breakdowns, PM and modifications, with its own MTBF and MTTR', false, 500, 0, 6000, 40)
on conflict (product_code, name) do nothing;
delete from console.app_features f where f.product_code = 'mnt' and f.name = 'Core platform'
   and not exists (select 1 from console.invoice_lines il where il.feature_id = f.id);
update console.app_features set price_year = price_month * 10 where product_code = 'mnt' and price_year = 0;
select console.sync_app_price('mnt');

-- a closed breakdown books its downtime in MMD loss hours; the link is the breakdown number
alter table console.mmd_loss add column if not exists ref text;

create table if not exists console.mnt_counters (
  customer_id uuid not null references console.customers(id) on delete cascade, key text not null, n bigint not null default 0, primary key (customer_id, key));
create table if not exists console.mnt_breakdowns (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  bd_no text not null, machine_code text not null, machine_name text,
  started_at timestamptz not null, attended_at timestamptz, ended_at timestamptz, shift text, reported_by text, attended_by text,
  problem text not null, category text, d_code text, root_cause text, action_taken text, preventive_action text, spares jsonb not null default '[]',
  status text not null default 'open' check (status in ('open', 'attended', 'closed', 'void')), void_reason text, closed_by text,
  sample boolean not null default false, created_by text, created_at timestamptz not null default now(),
  unique (customer_id, bd_no));
create table if not exists console.mnt_pm_plans (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  machine_code text not null, machine_name text, task text not null, frequency_days int not null check (frequency_days between 1 and 1100), est_min int,
  last_done date, next_due date not null, active boolean not null default true, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create table if not exists console.mnt_pm_log (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  plan_id uuid references console.mnt_pm_plans(id) on delete set null, machine_code text not null, task text not null,
  done_on date not null, due_on date, done_by text, duration_min int, findings text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create table if not exists console.mnt_events (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references console.customers(id) on delete cascade,
  machine_code text not null, event_date date not null, type text not null, description text not null, cost numeric, done_by text,
  status text not null default 'ok' check (status in ('ok', 'void')), void_reason text, sample boolean not null default false, created_by text, created_at timestamptz not null default now());
create index if not exists mnt_bd_machine on console.mnt_breakdowns (customer_id, machine_code, started_at);
create index if not exists mnt_pm_due on console.mnt_pm_plans (customer_id, next_due);
create index if not exists mnt_log_machine on console.mnt_pm_log (customer_id, machine_code, done_on);
create index if not exists mnt_ev_machine on console.mnt_events (customer_id, machine_code, event_date);
do $$ declare t text; begin foreach t in array array['mnt_counters','mnt_breakdowns','mnt_pm_plans','mnt_pm_log','mnt_events'] loop
  execute format('alter table console.%I enable row level security', t);
  execute format('drop policy if exists %I on console.%I', t || '_staff', t);
  execute format('create policy %I on console.%I for all to authenticated using (console.is_staff()) with check (console.is_staff())', t || '_staff', t);
end loop; end $$;

-- ---------- helpers ----------
create or replace function console.mnt_next(p_cid uuid, p_key text) returns bigint language sql security definer set search_path = console, public as $$
  insert into console.mnt_counters (customer_id, key, n) values (p_cid, p_key, 1)
  on conflict (customer_id, key) do update set n = console.mnt_counters.n + 1 returning n $$;
revoke all on function console.mnt_next(uuid, text) from public, anon, authenticated;

-- a closed breakdown books its downtime in MMD loss hours (one row per calendar day) against the chosen D code
create or replace function console.mnt_book_loss(p_cid uuid, p_bd uuid, p_me text) returns void language plpgsql security definer set search_path = console, public as $$
declare b console.mnt_breakdowns%rowtype; t timestamptz; nxt timestamptz; mins numeric; dn text; ist text := 'Asia/Kolkata';
begin
  select * into b from console.mnt_breakdowns where id = p_bd;
  delete from console.mmd_loss where customer_id = p_cid and ref = b.bd_no;
  if b.d_code is null or b.ended_at is null or not exists (select 1 from console.licences where customer_id = p_cid and product_code = 'mmd') then return; end if;
  select name into dn from console.ops_records where customer_id = p_cid and kind = 'loss_codes' and code = b.d_code;
  t := b.started_at;
  while t < b.ended_at loop
    nxt := least(b.ended_at, ((date_trunc('day', t at time zone ist) + interval '1 day') at time zone ist));
    mins := round(extract(epoch from (nxt - t)) / 60);
    if mins >= 1 then
      insert into console.mmd_loss (customer_id, loss_date, shift, machine_code, d_code, d_name, minutes, remark, operator, ref, sample, created_by)
      values (p_cid, (t at time zone ist)::date, b.shift, b.machine_code, b.d_code, dn, least(1440, mins), 'Breakdown ' || b.bd_no || ': ' || left(b.problem, 120), b.reported_by, b.bd_no, b.sample, p_me);
    end if;
    t := nxt;
  end loop;
end $$;
revoke all on function console.mnt_book_loss(uuid, uuid, text) from public, anon, authenticated;

create or replace function console.mnt_freq(p text) returns int language sql immutable as $$
  select case lower(coalesce(p, '')) when 'daily' then 1 when 'weekly' then 7 when 'monthly' then 30 when 'quarterly' then 90 when 'half-yearly' then 182 when 'yearly' then 365 else null end $$;

-- ---------- reads ----------
create or replace function public.kmr_mnt_load(p_slug text) returns jsonb language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.qp_cid(p_slug, 'mnt');
begin
  return jsonb_build_object(
    'machines', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'machines' and r.active), '[]'),
    'loss_codes', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'loss_codes' and r.active), '[]'),
    'shifts', coalesce((select jsonb_agg(jsonb_build_object('code', r.code, 'name', r.name) || r.data order by r.code) from console.ops_records r where r.customer_id = cid and r.kind = 'shifts' and r.active), '[]'),
    'plant', (select r.data from console.ops_records r where r.customer_id = cid and r.kind = 'plant_standards' and r.active order by r.code limit 1),
    'has_mmd', exists (select 1 from console.licences where customer_id = cid and product_code = 'mmd'),
    'today', (now() at time zone 'Asia/Kolkata')::date, 'now', now());
end $$;

create or replace function public.kmr_mnt_data(p_slug text, p_days int default 180) returns jsonb language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.qp_cid(p_slug, 'mnt'); since timestamptz := now() - make_interval(days => greatest(7, least(coalesce(p_days, 180), 1100)));
begin
  return jsonb_build_object(
    'breakdowns', coalesce((select jsonb_agg(to_jsonb(b) - 'customer_id' order by b.started_at desc) from console.mnt_breakdowns b where b.customer_id = cid and b.status <> 'void' and (b.status in ('open', 'attended') or b.started_at >= since or b.ended_at >= since)), '[]'),
    'plans', coalesce((select jsonb_agg(to_jsonb(p) - 'customer_id' order by p.next_due, p.machine_code) from console.mnt_pm_plans p where p.customer_id = cid and p.active), '[]'),
    'pm_log', coalesce((select jsonb_agg(to_jsonb(l) - 'customer_id' order by l.done_on desc, l.created_at desc) from console.mnt_pm_log l where l.customer_id = cid and l.status = 'ok' and l.done_on >= (since at time zone 'Asia/Kolkata')::date), '[]'),
    'events', coalesce((select jsonb_agg(to_jsonb(e) - 'customer_id' order by e.event_date desc) from console.mnt_events e where e.customer_id = cid and e.status = 'ok' and e.event_date >= (since at time zone 'Asia/Kolkata')::date), '[]'),
    'losses', case when exists (select 1 from console.licences where customer_id = cid and product_code = 'mmd')
                   then coalesce((select jsonb_agg(jsonb_build_object('loss_date', l.loss_date, 'machine_code', l.machine_code, 'd_code', l.d_code, 'd_name', l.d_name, 'minutes', l.minutes) order by l.loss_date desc)
                                    from console.mmd_loss l where l.customer_id = cid and l.status = 'ok' and l.ref is null and l.loss_date >= (since at time zone 'Asia/Kolkata')::date), '[]') else '[]'::jsonb end,
    'today', (now() at time zone 'Asia/Kolkata')::date, 'now', now());
end $$;

-- the machine history card: everything ever recorded for one machine
create or replace function public.kmr_mnt_card(p_slug text, p_machine text) returns jsonb language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.qp_cid(p_slug, 'mnt'); m record;
begin
  perform console.require_feature(p_slug, 'mnt', 'mnt.machine-history-card');
  select r.code, r.name, r.data into m from console.ops_records r where r.customer_id = cid and r.kind = 'machines' and r.code = p_machine;
  if not found then raise exception 'Machine “%” is not in Operations Master › Machines.', coalesce(p_machine, ''); end if;
  return jsonb_build_object('machine', jsonb_build_object('code', m.code, 'name', m.name) || m.data,
    'breakdowns', coalesce((select jsonb_agg(to_jsonb(b) - 'customer_id' order by b.started_at desc) from console.mnt_breakdowns b where b.customer_id = cid and b.machine_code = p_machine and b.status <> 'void'), '[]'),
    'pm_log', coalesce((select jsonb_agg(to_jsonb(l) - 'customer_id' order by l.done_on desc) from console.mnt_pm_log l where l.customer_id = cid and l.machine_code = p_machine and l.status = 'ok'), '[]'),
    'events', coalesce((select jsonb_agg(to_jsonb(e) - 'customer_id' order by e.event_date desc) from console.mnt_events e where e.customer_id = cid and e.machine_code = p_machine and e.status = 'ok'), '[]'),
    'plans', coalesce((select jsonb_agg(to_jsonb(p) - 'customer_id' order by p.next_due) from console.mnt_pm_plans p where p.customer_id = cid and p.machine_code = p_machine and p.active), '[]'),
    'today', (now() at time zone 'Asia/Kolkata')::date, 'now', now());
end $$;

-- ---------- breakdowns ----------
create or replace function public.kmr_mnt_bd_start(p_slug text, p jsonb) returns jsonb language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); mc text := trim(coalesce(p ->> 'machine_code', '')); mn text; st timestamptz := coalesce(nullif(p ->> 'started_at', '')::timestamptz, now()); pr text := trim(coalesce(p ->> 'problem', ''));
        v_id uuid; no text; me text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  select name into mn from console.ops_records where customer_id = cid and kind = 'machines' and code = mc;
  if mn is null and not exists (select 1 from console.ops_records where customer_id = cid and kind = 'machines' and code = mc) then raise exception 'Choose the machine (Operations Master › Machines).'; end if;
  if pr = '' then raise exception 'Describe the problem.'; end if;
  if st > now() + interval '5 minutes' then raise exception 'The breakdown cannot start in the future.'; end if;
  if exists (select 1 from console.mnt_breakdowns where customer_id = cid and machine_code = mc and status in ('open', 'attended')) then raise exception 'Machine % already has an open breakdown. Close it first.', mc; end if;
  no := 'BD-' || to_char(st at time zone 'Asia/Kolkata', 'YYMM') || '-' || lpad(console.mnt_next(cid, 'BD-' || to_char(st at time zone 'Asia/Kolkata', 'YYMM'))::text, 4, '0');
  insert into console.mnt_breakdowns (customer_id, bd_no, machine_code, machine_name, started_at, shift, reported_by, problem, category, created_by)
  values (cid, no, mc, mn, st, nullif(p ->> 'shift', ''), coalesce(nullif(trim(p ->> 'reported_by'), ''), me), pr, nullif(p ->> 'category', ''), me) returning id into v_id;
  return (select to_jsonb(b) - 'customer_id' from console.mnt_breakdowns b where b.id = v_id);
end $$;

create or replace function public.kmr_mnt_bd_attend(p_slug text, p_id uuid, p jsonb) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); b console.mnt_breakdowns%rowtype; at timestamptz := coalesce(nullif(p ->> 'attended_at', '')::timestamptz, now());
begin
  select * into b from console.mnt_breakdowns where id = p_id and customer_id = cid for update;
  if not found or b.status <> 'open' then raise exception 'Only a breakdown that is waiting for attention can be marked as attended.'; end if;
  if at < b.started_at then raise exception 'Attended time is before the breakdown started.'; end if;
  update console.mnt_breakdowns set attended_at = at, attended_by = coalesce(nullif(trim(p ->> 'attended_by'), ''), lower(coalesce(auth.jwt() ->> 'email', ''))), status = 'attended' where id = p_id;
end $$;

create or replace function public.kmr_mnt_bd_close(p_slug text, p_id uuid, p jsonb) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); b console.mnt_breakdowns%rowtype; en timestamptz := coalesce(nullif(p ->> 'ended_at', '')::timestamptz, now()); dc text := nullif(trim(coalesce(p ->> 'd_code', '')), '');
        me text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  select * into b from console.mnt_breakdowns where id = p_id and customer_id = cid for update;
  if not found or b.status not in ('open', 'attended') then raise exception 'This breakdown is already closed.'; end if;
  if en <= b.started_at then raise exception 'The machine cannot be restored before the breakdown started.'; end if;
  if en > now() + interval '5 minutes' then raise exception 'The restore time cannot be in the future.'; end if;
  if coalesce(trim(p ->> 'category'), '') = '' then raise exception 'Choose the cause category.'; end if;
  if coalesce(trim(p ->> 'root_cause'), '') = '' then raise exception 'Enter the root cause.'; end if;
  if coalesce(trim(p ->> 'action_taken'), '') = '' then raise exception 'Enter the corrective action taken.'; end if;
  if dc is not null and not exists (select 1 from console.ops_records where customer_id = cid and kind = 'loss_codes' and code = dc) then raise exception 'Loss code % is not in Operations Master › Loss codes.', dc; end if;
  update console.mnt_breakdowns set ended_at = en, status = 'closed', closed_by = me, category = trim(p ->> 'category'), d_code = dc, root_cause = trim(p ->> 'root_cause'), action_taken = trim(p ->> 'action_taken'),
         preventive_action = nullif(trim(coalesce(p ->> 'preventive_action', '')), ''), spares = coalesce(case when jsonb_typeof(p -> 'spares') = 'array' then p -> 'spares' end, '[]'), attended_by = coalesce(attended_by, nullif(trim(p ->> 'attended_by'), '')),
         attended_at = coalesce(attended_at, nullif(p ->> 'attended_at', '')::timestamptz) where id = p_id;
  perform console.mnt_book_loss(cid, p_id, me);
end $$;

create or replace function public.kmr_mnt_bd_void(p_slug text, p_id uuid, p_reason text) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); b console.mnt_breakdowns%rowtype;
begin
  if coalesce(trim(p_reason), '') = '' then raise exception 'Give the reason for voiding the breakdown.'; end if;
  select * into b from console.mnt_breakdowns where id = p_id and customer_id = cid for update;
  if not found or b.status = 'void' then raise exception 'Breakdown not found.'; end if;
  update console.mnt_breakdowns set status = 'void', void_reason = trim(p_reason) where id = p_id;
  delete from console.mmd_loss where customer_id = cid and ref = b.bd_no;
end $$;

-- ---------- preventive maintenance ----------
create or replace function public.kmr_mnt_pm_save(p_slug text, p jsonb) returns uuid language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); v_id uuid := nullif(p ->> 'id', '')::uuid; mc text := trim(coalesce(p ->> 'machine_code', '')); fq int := nullif(p ->> 'frequency_days', '')::int; nd date := nullif(p ->> 'next_due', '')::date;
        mn text; today date := (now() at time zone 'Asia/Kolkata')::date;
begin
  perform console.require_feature(p_slug, 'mnt', 'mnt.preventive-maintenance');
  select name into mn from console.ops_records where customer_id = cid and kind = 'machines' and code = mc;
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'machines' and code = mc) then raise exception 'Choose the machine.'; end if;
  if coalesce(trim(p ->> 'task'), '') = '' then raise exception 'Enter the maintenance task.'; end if;
  if fq is null or fq < 1 or fq > 1100 then raise exception 'Enter the frequency in days (1–1100).'; end if;
  if v_id is null then
    insert into console.mnt_pm_plans (customer_id, machine_code, machine_name, task, frequency_days, est_min, next_due, created_by)
    values (cid, mc, mn, trim(p ->> 'task'), fq, nullif(p ->> 'est_min', '')::int, coalesce(nd, today + fq), lower(coalesce(auth.jwt() ->> 'email', ''))) returning id into v_id;
  else
    update console.mnt_pm_plans set machine_code = mc, machine_name = mn, task = trim(p ->> 'task'), frequency_days = fq, est_min = nullif(p ->> 'est_min', '')::int, next_due = coalesce(nd, next_due), active = coalesce((p ->> 'active')::boolean, true)
     where id = v_id and customer_id = cid;
  end if;
  return v_id;
end $$;

-- one plan per machine from the PM frequency written in the Operations Master (Weekly, Monthly, Quarterly, Half-yearly, Yearly); first due dates are spread over the period
create or replace function public.kmr_mnt_pm_seed(p_slug text) returns integer language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); r record; n int := 0; fq int; today date := (now() at time zone 'Asia/Kolkata')::date;
begin
  perform console.require_feature(p_slug, 'mnt', 'mnt.preventive-maintenance');
  for r in select code, name, data ->> 'pm_frequency' pf from console.ops_records where customer_id = cid and kind = 'machines' and active loop
    fq := console.mnt_freq(r.pf);
    if fq is null or exists (select 1 from console.mnt_pm_plans where customer_id = cid and machine_code = r.code and active) then continue; end if;
    insert into console.mnt_pm_plans (customer_id, machine_code, machine_name, task, frequency_days, next_due, created_by)
    values (cid, r.code, r.name, 'Preventive maintenance as per the PM checklist (' || r.pf || ')', fq, today + (abs(hashtext(r.code)) % fq), lower(coalesce(auth.jwt() ->> 'email', '')));
    n := n + 1;
  end loop;
  return n;
end $$;

create or replace function public.kmr_mnt_pm_done(p_slug text, p_plan uuid, p jsonb) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); pl console.mnt_pm_plans%rowtype; dn date := coalesce(nullif(p ->> 'done_on', '')::date, (now() at time zone 'Asia/Kolkata')::date); me text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  perform console.require_feature(p_slug, 'mnt', 'mnt.preventive-maintenance');
  select * into pl from console.mnt_pm_plans where id = p_plan and customer_id = cid for update;
  if not found then raise exception 'Plan not found.'; end if;
  if dn > (now() at time zone 'Asia/Kolkata')::date then raise exception 'The date done cannot be in the future.'; end if;
  insert into console.mnt_pm_log (customer_id, plan_id, machine_code, task, done_on, due_on, done_by, duration_min, findings, created_by)
  values (cid, pl.id, pl.machine_code, pl.task, dn, pl.next_due, coalesce(nullif(trim(p ->> 'done_by'), ''), me), nullif(p ->> 'duration_min', '')::int, nullif(trim(coalesce(p ->> 'findings', '')), ''), me);
  update console.mnt_pm_plans set last_done = greatest(coalesce(last_done, dn), dn), next_due = greatest(coalesce(last_done, dn), dn) + frequency_days where id = pl.id;
end $$;

create or replace function public.kmr_mnt_pm_void(p_slug text, p_log uuid, p_reason text) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); l console.mnt_pm_log%rowtype; ld date;
begin
  perform console.require_feature(p_slug, 'mnt', 'mnt.preventive-maintenance');
  if coalesce(trim(p_reason), '') = '' then raise exception 'Give the reason for voiding the record.'; end if;
  select * into l from console.mnt_pm_log where id = p_log and customer_id = cid for update;
  if not found or l.status = 'void' then raise exception 'Record not found.'; end if;
  update console.mnt_pm_log set status = 'void', void_reason = trim(p_reason) where id = p_log;
  if l.plan_id is not null then
    select max(done_on) into ld from console.mnt_pm_log where plan_id = l.plan_id and status = 'ok';
    update console.mnt_pm_plans set last_done = ld, next_due = case when ld is null then coalesce(l.due_on, next_due) else ld + frequency_days end where id = l.plan_id;
  end if;
end $$;

-- ---------- machine history: modifications, overhauls, spares, relocations ----------
create or replace function public.kmr_mnt_event_save(p_slug text, p jsonb) returns uuid language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt'); mc text := trim(coalesce(p ->> 'machine_code', '')); v_id uuid;
begin
  if not exists (select 1 from console.ops_records where customer_id = cid and kind = 'machines' and code = mc) then raise exception 'Choose the machine.'; end if;
  if coalesce(trim(p ->> 'type'), '') = '' then raise exception 'Choose the type of entry.'; end if;
  if coalesce(trim(p ->> 'description'), '') = '' then raise exception 'Describe what was done.'; end if;
  insert into console.mnt_events (customer_id, machine_code, event_date, type, description, cost, done_by, created_by)
  values (cid, mc, coalesce(nullif(p ->> 'event_date', '')::date, (now() at time zone 'Asia/Kolkata')::date), trim(p ->> 'type'), trim(p ->> 'description'), nullif(p ->> 'cost', '')::numeric, nullif(trim(coalesce(p ->> 'done_by', '')), ''), lower(coalesce(auth.jwt() ->> 'email', ''))) returning id into v_id;
  return v_id;
end $$;
create or replace function public.kmr_mnt_event_void(p_slug text, p_id uuid, p_reason text) returns void language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.qp_edit(p_slug, 'mnt');
begin
  if coalesce(trim(p_reason), '') = '' then raise exception 'Give the reason for voiding the entry.'; end if;
  update console.mnt_events set status = 'void', void_reason = trim(p_reason) where id = p_id and customer_id = cid;
end $$;

-- ---------- sample data: breakdowns in every state, PM plans (some overdue), history entries ----------
create or replace function console.mnt_sample(p_cid uuid, p_action text) returns integer language plpgsql security definer set search_path = console, public as $$
declare n int := 0; k int; me text := 'sample'; ist text := 'Asia/Kolkata'; today date := (now() at time zone 'Asia/Kolkata')::date; m record; i int := 0; j int; cnt int; d int; hr int; dur int; st timestamptz; en timestamptz; bid uuid;
        cats text[] := array['Mechanical', 'Electrical', 'Hydraulic / pneumatic', 'Tooling', 'Control / software', 'Utilities', 'Mechanical', 'Electrical'];
        probs text[] := array['Spindle bearing noise and heat', 'Servo drive fault alarm', 'Hydraulic chuck pressure drop', 'Turret not indexing', 'Controller hang / restart', 'Coolant pump failure', 'Axis backlash high', 'Limit switch fault'];
        roots text[] := array['Bearing worn — lubrication interval exceeded', 'Loose connector at drive', 'Leaking seal on chuck cylinder', 'Index sensor misaligned', 'Corrupted parameter file', 'Impeller choked with swarf', 'Ball screw nut wear', 'Switch damaged by coolant'];
        acts text[] := array['Replaced spindle bearing, regreased', 'Re-seated and locked connector', 'Replaced cylinder seal kit', 'Re-aligned sensor and tested 50 indexes', 'Restored parameters from backup', 'Cleaned pump and fitted strainer', 'Adjusted nut preload', 'Replaced switch, sealed cable gland'];
        prev text[] := array['Add bearing greasing to weekly PM', 'Torque-mark connectors; check monthly', 'Seal kit kept as critical spare', 'Add sensor check to weekly PM', 'Parameter backup after every change', 'Fit strainer; clean weekly', 'Check backlash quarterly', 'Cable glands to IP67 type'];
        dcs text[] := array['D01', 'D02', 'D03', 'D09', 'D01', 'D03', 'D01', 'D02'];
begin
  if p_action = 'flush' then
    delete from console.mmd_loss where customer_id = p_cid and sample and ref is not null; get diagnostics k = row_count; n := n + k;
    delete from console.mnt_pm_log where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.mnt_pm_plans where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.mnt_events where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    delete from console.mnt_breakdowns where customer_id = p_cid and sample; get diagnostics k = row_count; n := n + k;
    return n;
  end if;
  if exists (select 1 from console.mnt_breakdowns where customer_id = p_cid and sample) then return 0; end if;
  for m in select code, name, data from console.ops_records where customer_id = p_cid and kind = 'machines' and active order by code limit 8 loop
    i := i + 1;
    -- history: installation, and for some a modification
    insert into console.mnt_events (customer_id, machine_code, event_date, type, description, cost, done_by, sample, created_by)
    values (p_cid, m.code, today - (900 + i * 37), 'Installation', 'Installed and commissioned; trial run and accuracy check passed', null, 'Supplier engineer', true, me);
    if i % 3 = 0 then insert into console.mnt_events (customer_id, machine_code, event_date, type, description, cost, done_by, sample, created_by)
      values (p_cid, m.code, today - (200 + i * 11), 'Modification', 'Coolant filtration unit added', 38000, 'Maintenance', true, me); end if;
    if i % 4 = 1 then insert into console.mnt_events (customer_id, machine_code, event_date, type, description, cost, done_by, sample, created_by)
      values (p_cid, m.code, today - (320 + i * 5), 'Overhaul', 'Annual overhaul: spindle, guideways, hydraulics', 145000, 'OEM service', true, me); end if;
    -- breakdowns over the last 150 days: a few machines fail more often
    cnt := case when i % 4 = 2 then 9 when i % 3 = 0 then 6 else 4 end;
    for j in 1..cnt loop
      d := 6 + ((i * 17 + j * 29) % 140); hr := 6 + ((i * 5 + j * 3) % 14); dur := 25 + ((i * 37 + j * 53) % 260);
      st := ((today - d)::timestamp + make_interval(hours => hr)) at time zone ist; en := st + make_interval(mins => dur);
      insert into console.mnt_breakdowns (customer_id, bd_no, machine_code, machine_name, started_at, attended_at, ended_at, shift, reported_by, attended_by, problem, category, d_code, root_cause, action_taken, preventive_action, spares, status, closed_by, sample, created_by, created_at)
      values (p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM') || '-' || lpad(console.mnt_next(p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM'))::text, 4, '0'), m.code, m.name, st, st + make_interval(mins => 5 + (j * 7) % 20), en,
              case when hr < 14 then 'A' else 'B' end, 'Operator', 'Maintenance', probs[1 + (i + j) % 8], cats[1 + (i + j) % 8],
              case when exists (select 1 from console.ops_records where customer_id = p_cid and kind = 'loss_codes' and code = dcs[1 + (i + j) % 8]) then dcs[1 + (i + j) % 8] end,
              roots[1 + (i + j) % 8], acts[1 + (i + j) % 8], prev[1 + (i + j) % 8], case when (i + j) % 3 = 0 then '[{"spare": "Bearing set", "qty": 1}]'::jsonb else '[]'::jsonb end, 'closed', me, true, me, st) returning id into bid;
      perform console.mnt_book_loss(p_cid, bid, me); n := n + 1;
    end loop;
    -- two machines have a breakdown right now
    if i = 2 then
      st := now() - interval '95 minutes';
      insert into console.mnt_breakdowns (customer_id, bd_no, machine_code, machine_name, started_at, shift, reported_by, problem, category, status, sample, created_by)
      values (p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM') || '-' || lpad(console.mnt_next(p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM'))::text, 4, '0'), m.code, m.name, st, 'A', 'Operator', 'Spindle will not start — drive alarm', 'Electrical', 'open', true, me); n := n + 1;
    elsif i = 4 then
      st := now() - interval '3 hours';
      insert into console.mnt_breakdowns (customer_id, bd_no, machine_code, machine_name, started_at, attended_at, attended_by, shift, reported_by, problem, category, status, sample, created_by)
      values (p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM') || '-' || lpad(console.mnt_next(p_cid, 'BD-' || to_char(st at time zone ist, 'YYMM'))::text, 4, '0'), m.code, m.name, st, st + interval '20 minutes', 'Maintenance', 'A', 'Operator', 'Coolant leak at the tank — pump replacement awaited', 'Utilities', 'attended', true, me); n := n + 1;
    end if;
    -- PM plans: weekly lubrication and a monthly PM; some overdue
    insert into console.mnt_pm_plans (customer_id, machine_code, machine_name, task, frequency_days, est_min, last_done, next_due, sample, created_by)
    values (p_cid, m.code, m.name, 'Weekly: lubrication, cleaning, coolant level, guard and safety check', 7, 45, today - (3 + i % 6), today - (3 + i % 6) + 7, true, me),
           (p_cid, m.code, m.name, 'Monthly PM: filters, belts, alignment check, electrical tightness', 30, 180, today - (12 + i * 4), today - (12 + i * 4) + 30, true, me);
    for j in 1..3 loop
      insert into console.mnt_pm_log (customer_id, plan_id, machine_code, task, done_on, due_on, done_by, duration_min, findings, sample, created_by)
      select p_cid, pl.id, m.code, pl.task, today - (3 + i % 6) - 7 * (j - 1), today - (3 + i % 6) - 7 * (j - 1), 'Maintenance', 40 + j, case when j = 1 then 'OK' else 'OK — minor oil top-up' end, true, me from console.mnt_pm_plans pl where pl.customer_id = p_cid and pl.machine_code = m.code and pl.sample and pl.frequency_days = 7 limit 1;
    end loop;
    n := n + 5;
  end loop;
  return n;
end $$;
revoke all on function console.mnt_sample(uuid, text) from public, anon, authenticated;

-- ---------- portal, access, Data Master and Grand Master: re-created from their latest version ----------
create or replace function console.data_target(p_slug text, p_app text, out cid uuid, out ref uuid)
language plpgsql stable security definer set search_path = console, public as $$
begin
  select c.id into cid from console.customers c where c.slug = lower(p_slug);
  if cid is null or not console.is_customer_admin(cid) then raise exception 'Only your company administrator can manage app data.'; end if;
  if p_app = 'ops' then ref := cid; return; end if;
  if p_app in ('sales','calib','apqp','ppap','rmp','mmd','mnt') then
    if not console.has_app(cid, p_app) then raise exception 'Your company does not have this app yet.'; end if;
    ref := cid; return;
  end if;
  if p_app not in ('hrm','balloon','pd','capacity') then raise exception 'Unknown app %', p_app; end if;
  select l.product_ref into ref from console.licences l where l.customer_id = cid and l.product_code = p_app and l.product_ref is not null limit 1;
  if ref is null then raise exception 'Your company does not have this app yet.'; end if;
end $$;
revoke all on function console.data_target(text, text) from public, anon, authenticated;

create or replace function console.app2_tables(p_app text) returns text[] language sql immutable as $$
  select case p_app when 'sales' then array['sf_lines','sf_despatch','sf_actions']
                    when 'calib' then array['cal_instruments','cal_records','cal_events','cal_oot','cal_msa']
                    when 'apqp'  then array['apqp_projects','apqp_items']
                    when 'ppap'  then array['ppap_submissions']
                    when 'rmp'   then array['rmp_bom','rmp_stock','rmp_demand','rmp_orders']
                    when 'mmd'   then array['mmd_counters','mmd_route_sheets','mmd_tags','mmd_dcs','mmd_entries','mmd_defects','mmd_grns','mmd_loss']
                    when 'mnt'   then array['mnt_counters','mnt_breakdowns','mnt_pm_plans','mnt_pm_log','mnt_events'] end
$$;


create or replace function console.app2_export(p_app text, p_cid uuid, p_real_only boolean) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare t text; rows jsonb; tabs jsonb := '{}'; parent text;
begin
  foreach t in array console.app2_tables(p_app) loop
    parent := case when t in ('sf_lines','sf_actions','cal_instruments','apqp_projects','ppap_submissions','rmp_bom','rmp_stock','rmp_demand','rmp_orders','mmd_counters','mmd_route_sheets','mmd_tags','mmd_dcs','mmd_entries','mmd_defects','mmd_grns','mmd_loss','mnt_counters','mnt_breakdowns','mnt_pm_plans','mnt_pm_log','mnt_events') then null when p_app = 'sales' then 'sf_lines' when p_app = 'calib' then 'cal_instruments' else 'apqp_projects' end;
    if not p_real_only then
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x where x.customer_id = $1', t) into rows using p_cid;
    elsif parent is null then
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x where x.customer_id = $1 and not x.sample', t) into rows using p_cid;
    else
      execute format('select coalesce(jsonb_agg(to_jsonb(x) - ''customer_id''), ''[]'') from console.%I x join console.%I p on p.id = x.%I where x.customer_id = $1 and not p.sample',
                     t, parent, case parent when 'sf_lines' then 'line_id' when 'apqp_projects' then 'project_id' else 'instrument_id' end) into rows using p_cid;
    end if;
    tabs := tabs || jsonb_build_object(t, rows);
  end loop;
  return tabs;
end $$;
revoke all on function console.app2_export(text, uuid, boolean), console.app2_clear(text, uuid, boolean), console.app2_restore(text, uuid, jsonb, boolean) from public, anon, authenticated;

create or replace function console.app2_clear(p_app text, p_cid uuid, p_real_only boolean) returns bigint
language plpgsql security definer set search_path = console, public as $$
declare n bigint := 0; k bigint;
begin
  if p_app = 'sales' then
    delete from console.sf_actions where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.sf_lines where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
  elsif p_app = 'calib' then
    delete from console.cal_instruments where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'apqp' then
    delete from console.apqp_projects where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'ppap' then
    delete from console.ppap_submissions where customer_id = p_cid and (not p_real_only or not sample); get diagnostics n = row_count;
  elsif p_app = 'rmp' then
    delete from console.rmp_orders where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_demand where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_bom where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.rmp_stock where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
  elsif p_app = 'mmd' then
    delete from console.mmd_loss where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;
    delete from console.mmd_route_sheets where customer_id = p_cid and (not p_real_only or not sample); get diagnostics k = row_count; n := n + k;   -- tags, entries, defects, DCs and GRNs go with their route sheet
    if not p_real_only then delete from console.mmd_counters where customer_id = p_cid; end if;
  elsif p_app = 'mnt' then
    delete from console.mmd_loss where customer_id = p_cid and ref is not null and (not p_real_only or sample); get diagnostics k = row_count; n := n + k;
    delete from console.mnt_pm_log where customer_id = p_cid and (not p_real_only or sample); get diagnostics k = row_count; n := n + k;
    delete from console.mnt_pm_plans where customer_id = p_cid and (not p_real_only or sample); get diagnostics k = row_count; n := n + k;
    delete from console.mnt_events where customer_id = p_cid and (not p_real_only or sample); get diagnostics k = row_count; n := n + k;
    delete from console.mnt_breakdowns where customer_id = p_cid and (not p_real_only or sample); get diagnostics k = row_count; n := n + k;
    if not p_real_only then delete from console.mnt_counters where customer_id = p_cid; end if;
  end if;
  return n;
end $$;


create or replace function console.app2_restore(p_app text, p_cid uuid, p_tables jsonb, p_real_only boolean) returns bigint
language plpgsql security definer set search_path = console, public as $$
declare t text; rows jsonb; tot bigint := 0; k bigint;
begin
  perform console.app2_clear(p_app, p_cid, p_real_only);
  foreach t in array console.app2_tables(p_app) loop
    -- every row goes back into THIS company, whatever the file says; restored real data is never marked sample
    rows := (select coalesce(jsonb_agg(r || jsonb_build_object('customer_id', p_cid)
                       || case when t in ('sf_lines','sf_actions','cal_instruments','apqp_projects','ppap_submissions','rmp_bom','rmp_stock','rmp_demand','rmp_orders','mmd_counters','mmd_route_sheets','mmd_tags','mmd_dcs','mmd_entries','mmd_defects','mmd_grns','mmd_loss','mnt_counters','mnt_breakdowns','mnt_pm_plans','mnt_pm_log','mnt_events') and p_real_only then '{"sample":false}'::jsonb else '{}'::jsonb end), '[]')
               from jsonb_array_elements(coalesce(p_tables -> t, '[]')) r);
    execute format('insert into console.%I select * from jsonb_populate_recordset(null::console.%I, $1) on conflict do nothing', t, t) using rows;
    get diagnostics k = row_count; tot := tot + k;
  end loop;
  return tot;
end $$;


create or replace function public.kmr_qp_context(p_slug text, p_code text) returns jsonb language sql stable security definer set search_path = console, public as $$
  select case when console.qp_role(c.id, p_code) is null then null else jsonb_build_object('role', console.qp_role(c.id, p_code), 'company', c.name) end
    from console.customers c where c.slug = lower(p_slug) and p_code in ('apqp', 'ppap', 'rmp', 'mmd', 'mnt') $$;


create or replace function public.kmr_portal(p_slug text)
returns table (product_code text, product_name text, app_path text, purchased boolean, ok boolean, status text,
               valid_until date, message text, customer_name text, logo_url text, product_slug text,
               has_access boolean, is_contact boolean)
language plpgsql stable security definer set search_path = console, public as $$
declare
  em text := lower(coalesce(auth.jwt() ->> 'email', ''));
  uid uuid := auth.uid();
  c console.customers%rowtype;
  member boolean := false;
begin
  select * into c from console.customers where slug = lower(p_slug);
  if c.id is null or em = '' then return; end if;
  select true into member from console.licences l
   where l.customer_id = c.id and (
         (l.product_code = 'balloon'  and exists (select 1 from public.bi_members m where m.org_id = l.product_ref and lower(m.email) = em))
      or (l.product_code = 'pd'       and exists (select 1 from public.pd_members m where m.org_id = l.product_ref and lower(m.email) = em))
      or (l.product_code = 'capacity' and exists (select 1 from public.cp_members m where m.org_id = l.product_ref and m.email = em))
      or (l.product_code = 'sales'    and console.sf_member(l.customer_id, em))
      or (l.product_code = 'calib'    and console.cal_member(l.customer_id, em))
      or (l.product_code in ('apqp', 'ppap', 'rmp', 'mmd', 'mnt') and console.qp_member(l.customer_id, em, l.product_code))
      or (l.product_code = 'hrm'      and exists (select 1 from hrm.app_users u where u.tenant_id = l.product_ref and u.id = uid and u.active)))
   limit 1;
  if not coalesce(member, false) and lower(coalesce(c.contact_email, '')) <> em then return; end if;
  return query
    select p.code, p.name, p.app_path, (l.id is not null), coalesce(a.ok, false), coalesce(a.status, 'not_purchased'),
           l.valid_until, a.message, c.name, c.logo_url, l.product_slug,
           case p.code
             when 'balloon'  then exists (select 1 from public.bi_members m where m.org_id = l.product_ref and lower(m.email) = em)
             when 'pd'       then exists (select 1 from public.pd_members m where m.org_id = l.product_ref and lower(m.email) = em)
             when 'capacity' then exists (select 1 from public.cp_members m where m.org_id = l.product_ref and m.email = em)
             when 'sales'    then console.sf_member(l.customer_id, em)
             when 'calib'    then console.cal_member(l.customer_id, em)
             when 'apqp'     then console.qp_member(l.customer_id, em, 'apqp')
             when 'ppap'     then console.qp_member(l.customer_id, em, 'ppap')
             when 'rmp'      then console.qp_member(l.customer_id, em, 'rmp')
             when 'mmd'      then console.qp_member(l.customer_id, em, 'mmd')
             when 'mnt'      then console.qp_member(l.customer_id, em, 'mnt')
             when 'hrm'      then exists (select 1 from hrm.app_users u where u.tenant_id = l.product_ref and u.id = uid and u.active)
             else false end,
           lower(coalesce(c.contact_email, '')) = em
      from console.products p
      left join console.licences l on l.product_code = p.code and l.customer_id = c.id
      left join lateral console.access_state(p.code, l.product_ref) a on l.id is not null
     where p.active
     order by p.sort_order;
end $$;
revoke all on function public.kmr_portal(text) from public, anon;
grant execute on function public.kmr_portal(text) to authenticated;

create or replace function public.kmr_portal_join(p_slug text, p_product text) returns text
language plpgsql security definer set search_path = console, public as $$
declare em text := lower(coalesce(auth.jwt() ->> 'email', '')); cid uuid; ok boolean;
begin
  select id into cid from console.customers where slug = lower(p_slug);
  if cid is null or em = '' then raise exception 'Unknown company link.'; end if;
  if not exists (select 1 from console.licences where customer_id = cid and product_code = p_product and product_ref is not null) then
    raise exception 'This app is not set up for your company yet. Please contact KMR.';
  end if;
  if console.is_customer_admin(cid) then
    perform console.grant_admins(cid);          -- administrators: admin in every bought tool
  end if;
  perform console.sync_member(cid, em);         -- everyone: whatever Administration › Users & access says
  ok := case p_product
    when 'balloon'  then exists (select 1 from public.bi_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'balloon' where l.customer_id = cid and lower(m.email) = em)
    when 'pd'       then exists (select 1 from public.pd_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'pd' where l.customer_id = cid and lower(m.email) = em)
    when 'capacity' then exists (select 1 from public.cp_members m join console.licences l on l.product_ref = m.org_id and l.product_code = 'capacity' where l.customer_id = cid and m.email = em)
    when 'sales'    then console.sf_member(cid, em)
    when 'calib'    then console.cal_member(cid, em)
    when 'apqp'     then console.qp_member(cid, em, 'apqp')
    when 'ppap'     then console.qp_member(cid, em, 'ppap')
    when 'rmp'      then console.qp_member(cid, em, 'rmp')
    when 'mmd'      then console.qp_member(cid, em, 'mmd')
    when 'mnt'      then console.qp_member(cid, em, 'mnt')
    when 'hrm'      then exists (select 1 from hrm.app_users u join console.licences l on l.product_ref = u.tenant_id and l.product_code = 'hrm' where l.customer_id = cid and u.id = auth.uid() and u.active)
    else false end;
  if not ok then
    raise exception 'You have not been given access to this app. Your company administrator can add it under KMR Apps › Administration › Users & access.';
  end if;
  return 'ok';
end $$;
revoke all on function public.kmr_portal_join(text, text) from public, anon;
grant execute on function public.kmr_portal_join(text, text) to authenticated;

create or replace function public.kmr_portal_stats(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare c uuid; out jsonb := '{}'; ref uuid; today date := (now() at time zone 'Asia/Kolkata')::date;
begin
  if not exists (select 1 from public.kmr_portal(p_slug)) then return out; end if;
  select id into c from console.customers where slug = lower(p_slug);
  select product_ref into ref from console.licences where customer_id = c and product_code = 'hrm';
  if ref is not null then
    out := out || jsonb_build_object('hrm', jsonb_build_object(
      'Employees', (select count(*) from hrm.employees where tenant_id = ref and status = 'active'),
      'In today', (select count(*) from hrm.attendance_days where tenant_id = ref and work_date = today and status in ('present','half_day','missed_punch')),
      'Awaiting approval', (select count(*) from hrm.leave_requests where tenant_id = ref and status = 'pending')
                          + (select count(*) from hrm.regularisation_requests where tenant_id = ref and status = 'pending')));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'balloon';
  if ref is not null then
    out := out || jsonb_build_object('balloon', jsonb_build_object(
      'Reports', (select count(*) from public.bi_reports where org_id = ref),
      'Users', (select count(*) from public.bi_members where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'pd';
  if ref is not null then
    out := out || jsonb_build_object('pd', jsonb_build_object(
      'Projects', (select count(*) from public.pd_projects where org_id = ref),
      'Users', (select count(*) from public.pd_members where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'capacity';
  if ref is not null then
    out := out || jsonb_build_object('capacity', jsonb_build_object(
      'Users', (select count(*) from public.cp_members where org_id = ref),
      'Saved versions', (select count(*) from public.cp_history where org_id = ref) + (select count(*) from public.cp_plans where org_id = ref)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'sales';
  if ref is not null then
    out := out || jsonb_build_object('sales', jsonb_build_object(
      'Users', (select count(*) from console.customer_members m where m.customer_id = c and coalesce(m.roles ->> 'sales', '') <> ''),
      'Parts planned', (select count(*) from console.sf_lines where customer_id = c and month = date_trunc('month', today)::date)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'calib';
  if ref is not null then
    out := out || jsonb_build_object('calib', jsonb_build_object(
      'Instruments', (select count(*) from console.cal_instruments where customer_id = c and status = 'In use'),
      'Overdue', (select count(*) from console.cal_instruments where customer_id = c and status = 'In use' and next_due < (now() at time zone 'Asia/Kolkata')::date)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'apqp';
  if ref is not null then
    out := out || jsonb_build_object('apqp', jsonb_build_object(
      'Programmes', (select count(*) from console.apqp_projects where customer_id = c and status = 'active'),
      'Open deliverables', (select count(*) from console.apqp_items i join console.apqp_projects p on p.id = i.project_id where i.customer_id = c and p.status = 'active' and i.status in ('open', 'progress')),
      'Overdue', (select count(*) from console.apqp_items i join console.apqp_projects p on p.id = i.project_id where i.customer_id = c and p.status = 'active' and i.status in ('open', 'progress') and i.due < today)));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'ppap';
  if ref is not null then
    out := out || jsonb_build_object('ppap', jsonb_build_object(
      'Submissions', (select count(*) from console.ppap_submissions where customer_id = c),
      'Awaiting approval', (select count(*) from console.ppap_submissions where customer_id = c and status = 'submitted'),
      'Approved', (select count(*) from console.ppap_submissions where customer_id = c and status in ('approved', 'interim'))));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'rmp';
  if ref is not null then
    out := out || jsonb_build_object('rmp', jsonb_build_object(
      'Materials', (select count(*) from console.rmp_stock where customer_id = c),
      'Orders placed', (select count(*) from console.rmp_orders where customer_id = c and status = 'ordered'),
      'Planned orders', (select count(*) from console.rmp_orders where customer_id = c and status = 'planned')));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'mmd';
  if ref is not null then
    out := out || jsonb_build_object('mmd', jsonb_build_object(
      'Open route sheets', (select count(*) from console.mmd_route_sheets where customer_id = c and status = 'open'),
      'Pieces in process', (select coalesce(sum(bal), 0) from console.mmd_tags where customer_id = c and status = 'open' and loc in ('op', 'rework')),
      'Open DCs', (select count(*) from console.mmd_dcs where customer_id = c and status in ('open', 'part'))));
  end if;
  select product_ref into ref from console.licences where customer_id = c and product_code = 'mnt';
  if ref is not null then
    out := out || jsonb_build_object('mnt', jsonb_build_object(
      'Open breakdowns', (select count(*) from console.mnt_breakdowns where customer_id = c and status in ('open', 'attended')),
      'PM overdue', (select count(*) from console.mnt_pm_plans where customer_id = c and active and next_due < (now() at time zone 'Asia/Kolkata')::date),
      'Breakdowns (30 days)', (select count(*) from console.mnt_breakdowns where customer_id = c and status <> 'void' and started_at >= now() - interval '30 days')));
  end if;
  return out;
end $$;
revoke all on function public.kmr_portal_stats(text) from public, anon;
grant execute on function public.kmr_portal_stats(text) to authenticated;

create or replace function public.kmr_data_overview(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid; l record; out jsonb := '[]'::jsonb; t text; n bigint; det jsonb; tot bigint; a text;
begin
  select id into cid from console.customers where slug = lower(p_slug);
  if cid is null or not console.is_customer_admin(cid) then raise exception 'Only your company administrator can manage app data.'; end if;
  for l in select product_code, product_ref from console.licences where customer_id = cid and product_ref is not null
             and product_code in ('hrm','balloon','pd','capacity') order by array_position(array['hrm','balloon','pd','capacity'], product_code) loop
    det := '{}'; tot := 0;
    if l.product_code = 'hrm' then
      foreach t in array array['employees','attendance_days','leave_requests','payroll_runs','loans','id_cards','onboarding_invites'] loop
        if to_regclass('hrm.' || t) is null then continue; end if;
        execute format('select count(*) from hrm.%I where tenant_id = $1', t) into n using l.product_ref;
        det := det || jsonb_build_object(t, n); tot := tot + n;
      end loop;
    else
      foreach t in array console.data_tables(l.product_code) loop
        execute format('select count(*) from public.%I where org_id = $1', t) into n using l.product_ref;
        det := det || jsonb_build_object(t, n); tot := tot + n;
      end loop;
    end if;
    out := out || jsonb_build_array(jsonb_build_object('app', l.product_code, 'records', tot, 'detail', det));
  end loop;
  foreach a in array array['sales','calib','apqp','ppap','rmp','mmd','mnt'] loop
    continue when not console.has_app(cid, a);
    det := '{}'; tot := 0;
    foreach t in array console.app2_tables(a) loop
      execute format('select count(*) from console.%I where customer_id = $1', t) into n using cid;
      det := det || jsonb_build_object(t, n); tot := tot + n;
    end loop;
    out := out || jsonb_build_array(jsonb_build_object('app', a, 'records', tot, 'detail', det));
  end loop;
  select count(*) into n from console.ops_records where customer_id = cid;
  out := out || jsonb_build_array(jsonb_build_object('app', 'ops', 'records', n, 'detail', jsonb_build_object('ops_records', n)));
  return out;
end $$;
grant execute on function public.kmr_data_overview(text) to authenticated;

create or replace function public.kmr_data_export(p_slug text, p_app text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare tg record; t text; rows jsonb; tabs jsonb := '{}';
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_app = 'hrm' then
    tabs := jsonb_build_object('hrm', hrm.company_export(tg.ref));
  elsif p_app = 'ops' then
    select coalesce(jsonb_agg(to_jsonb(r) - 'customer_id' order by r.kind, r.code), '[]') into rows from console.ops_records r where r.customer_id = tg.cid;
    tabs := jsonb_build_object('ops_records', rows);
  elsif p_app in ('sales','calib','apqp','ppap','rmp','mmd','mnt') then
    tabs := console.app2_export(p_app, tg.cid, false);
  else
    foreach t in array console.data_tables(p_app) loop
      execute format('select coalesce(jsonb_agg(to_jsonb(x)), ''[]'') from public.%I x where x.org_id = $1', t) into rows using tg.ref;
      tabs := tabs || jsonb_build_object(t, rows);
    end loop;
  end if;
  return jsonb_build_object('format', 'kmr-app-data', 'version', 1, 'app', p_app, 'company', lower(p_slug), 'exported_at', now(), 'tables', tabs);
end $$;
grant execute on function public.kmr_data_export(text, text) to authenticated;

create or replace function public.kmr_data_flush(p_slug text, p_app text, p_hrm_setup boolean default false) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare tg record;
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_app = 'hrm' then return hrm.company_flush(tg.ref, coalesce(p_hrm_setup, false)); end if;
  if p_app in ('sales','calib','apqp','ppap','rmp','mmd','mnt') then return jsonb_build_object('removed', console.app2_clear(p_app, tg.cid, false)); end if;
  return jsonb_build_object('removed', console.data_clear(p_app, tg.cid, tg.ref));
end $$;
grant execute on function public.kmr_data_flush(text, text, boolean) to authenticated;

create or replace function public.kmr_data_import(p_slug text, p_app text, p_data jsonb) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare tg record; t text; rows jsonb; n bigint; k bigint; tot bigint := 0; pass int; todo text[];
begin
  select * into tg from console.data_target(p_slug, p_app);
  if p_data ->> 'format' is distinct from 'kmr-app-data' then raise exception 'This is not a KMR Data Master file.'; end if;
  if p_data ->> 'app' is distinct from p_app then raise exception 'This file is a backup of another app (%).', p_data ->> 'app'; end if;
  if p_app = 'hrm' then
    return jsonb_build_object('restored', hrm.company_import(tg.ref, p_data -> 'tables' -> 'hrm'));
  end if;
  if p_app in ('sales','calib','apqp','ppap','rmp','mmd','mnt') then
    return jsonb_build_object('restored', console.app2_restore(p_app, tg.cid, p_data -> 'tables', false));
  end if;
  perform console.data_clear(p_app, tg.cid, tg.ref);
  if p_app = 'ops' then
    rows := (select coalesce(jsonb_agg(r || jsonb_build_object('customer_id', tg.cid)), '[]') from jsonb_array_elements(coalesce(p_data -> 'tables' -> 'ops_records', '[]')) r);
    insert into console.ops_records select * from jsonb_populate_recordset(null::console.ops_records, rows) on conflict do nothing;
    get diagnostics n = row_count;
    return jsonb_build_object('restored', n);
  end if;
  perform console.app_triggers(case p_app when 'balloon' then 'bi' when 'pd' then 'pd' else 'cp' end, false);
  todo := array(select x from unnest(console.data_tables(p_app)) x where (p_data -> 'tables') ? x);
  for pass in 1..4 loop
    exit when cardinality(todo) = 0;
    foreach t in array todo loop
      rows := (select coalesce(jsonb_agg(r || jsonb_build_object('org_id', tg.ref)), '[]') from jsonb_array_elements(p_data -> 'tables' -> t) r);
      begin
        execute format('insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1) on conflict do nothing', t, t) using rows;
        get diagnostics k = row_count; tot := tot + k; todo := array_remove(todo, t);
      exception when foreign_key_violation then null;
      end;
    end loop;
  end loop;
  perform console.app_triggers(case p_app when 'balloon' then 'bi' when 'pd' then 'pd' else 'cp' end, true);
  if cardinality(todo) > 0 then raise exception 'Could not restore: %.', array_to_string(todo, ', '); end if;
  return jsonb_build_object('restored', tot);
end $$;
grant execute on function public.kmr_data_import(text, text, jsonb) to authenticated;

create or replace function public.kmr_grand_sample(p_slug text, p_action text) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; r uuid; n int; k int; flow jsonb;
begin
  if p_action not in ('load','flush') then raise exception 'Unknown action.'; end if;
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    if p_action = 'load' then
      if exists (select 1 from hrm.employees where tenant_id = r and email like '%@demo.kmr.test') then n := 0;
      else n := hrm.demo_load(r); perform hrm.demo_payroll(r); end if;
      if to_regprocedure('hrm.demo_flow(uuid)') is not null then
        flow := hrm.demo_flow(r);
        out := out || jsonb_build_object('hrm_flow', flow);
      end if;
    else
      if exists (select 1 from information_schema.columns where table_schema = 'hrm' and table_name = 'candidates' and column_name = 'sample') then
        execute 'select count(*) from hrm.candidates where tenant_id = $1 and sample' into k using r;
        out := out || jsonb_build_object('hrm_candidates', k);
      end if;
      n := hrm.demo_flush(r);
    end if;
    out := out || jsonb_build_object('hrm', n, 'hrm_tenant', r);
  end if;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    out := out || jsonb_build_object('balloon', public.kmr_ops_sample_drawing(p_slug, p_action));
  end if;
  if p_action = 'load' then
    -- the Operations Master first: Sales Flow and Calibration Hub are built from its sample parts, rate contracts and gauges
    out := out || jsonb_build_object('ops', (public.kmr_ops_sample_load(p_slug) ->> 'added')::int);
    if console.has_app(cid, 'sales') then out := out || jsonb_build_object('sales', console.sf_sample(cid, 'load')); end if;
    if console.has_app(cid, 'calib') then out := out || jsonb_build_object('calib', console.cal_sample(cid, 'load')); end if;
    if console.has_app(cid, 'apqp') then out := out || jsonb_build_object('apqp', console.apqp_sample(cid, 'load')); end if;
    if console.has_app(cid, 'ppap') then out := out || jsonb_build_object('ppap', console.ppap_sample(cid, 'load')); end if;
    if console.has_app(cid, 'rmp') then out := out || jsonb_build_object('rmp', console.rmp_sample(cid, 'load')); end if;
    if console.has_app(cid, 'mmd') then out := out || jsonb_build_object('mmd', console.mmd_sample(cid, 'load')); end if;
    if console.has_app(cid, 'mnt') then out := out || jsonb_build_object('mnt', console.mnt_sample(cid, 'load')); end if;
  else
    if console.has_app(cid, 'sales') then out := out || jsonb_build_object('sales', console.sf_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'mnt') then out := out || jsonb_build_object('mnt', console.mnt_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'mmd') then out := out || jsonb_build_object('mmd', console.mmd_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'rmp') then out := out || jsonb_build_object('rmp', console.rmp_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'ppap') then out := out || jsonb_build_object('ppap', console.ppap_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'apqp') then out := out || jsonb_build_object('apqp', console.apqp_sample(cid, 'flush')); end if;
    if console.has_app(cid, 'calib') then out := out || jsonb_build_object('calib', console.cal_sample(cid, 'flush')); end if;
    out := out || jsonb_build_object('ops', public.kmr_ops_sample_flush(p_slug));
  end if;
  return out;
end $$;
revoke all on function public.kmr_grand_sample(text, text) from public, anon;
grant execute on function public.kmr_grand_sample(text, text) to authenticated;

create or replace function public.kmr_grand_overview(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); r uuid; real_ jsonb := '{}'; smp jsonb := '{}'; t text; n bigint; k bigint; c console.customers%rowtype;
begin
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    select count(*) filter (where coalesce(email, '') not like '%@demo.kmr.test'), count(*) filter (where coalesce(email, '') like '%@demo.kmr.test')
      into n, k from hrm.employees where tenant_id = r;
    real_ := real_ || jsonb_build_object('hrm', n); smp := smp || jsonb_build_object('hrm', k);
    if exists (select 1 from information_schema.columns where table_schema = 'hrm' and table_name = 'candidates' and column_name = 'sample') then
      execute 'select count(*) filter (where not sample), count(*) filter (where sample) from hrm.candidates where tenant_id = $1' into n, k using r;
      real_ := real_ || jsonb_build_object('hrm_candidates', n); smp := smp || jsonb_build_object('hrm_candidates', k);
    end if;
  end if;
  r := console.grand_ref(cid, 'balloon');
  if r is not null and to_regclass('public.bi_reports') is not null then
    execute 'select count(*) filter (where coalesce(file_path, '''') not like ''static:%''), count(*) filter (where file_path like ''static:%'') from public.bi_reports where org_id = $1'
      into n, k using r;
    real_ := real_ || jsonb_build_object('balloon', n); smp := smp || jsonb_build_object('balloon', k);
  end if;
  foreach t in array array['pd','capacity'] loop
    r := console.grand_ref(cid, t);
    if r is null then continue; end if;
    n := 0;
    declare tb text; m bigint; begin
      foreach tb in array console.data_tables(t) loop
        execute format('select count(*) from public.%I where org_id = $1', tb) into m using r; n := n + m;
      end loop;
    end;
    real_ := real_ || jsonb_build_object(t, n);
  end loop;
  if console.has_app(cid, 'sales') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.sf_lines where customer_id = cid;
    real_ := real_ || jsonb_build_object('sales', n); smp := smp || jsonb_build_object('sales', k);
  end if;
  if console.has_app(cid, 'calib') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.cal_instruments where customer_id = cid;
    real_ := real_ || jsonb_build_object('calib', n); smp := smp || jsonb_build_object('calib', k);
  end if;
  if console.has_app(cid, 'apqp') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.apqp_projects where customer_id = cid;
    real_ := real_ || jsonb_build_object('apqp', n); smp := smp || jsonb_build_object('apqp', k);
  end if;
  if console.has_app(cid, 'ppap') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.ppap_submissions where customer_id = cid;
    real_ := real_ || jsonb_build_object('ppap', n); smp := smp || jsonb_build_object('ppap', k);
  end if;
  if console.has_app(cid, 'rmp') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.rmp_stock where customer_id = cid;
    real_ := real_ || jsonb_build_object('rmp', n); smp := smp || jsonb_build_object('rmp', k);
  end if;
  if console.has_app(cid, 'mmd') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.mmd_route_sheets where customer_id = cid;
    real_ := real_ || jsonb_build_object('mmd', n); smp := smp || jsonb_build_object('mmd', k);
  end if;
  if console.has_app(cid, 'mnt') then
    select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.mnt_breakdowns where customer_id = cid;
    real_ := real_ || jsonb_build_object('mnt', n); smp := smp || jsonb_build_object('mnt', k);
  end if;
  select count(*) filter (where not sample), count(*) filter (where sample) into n, k from console.ops_records where customer_id = cid;
  real_ := real_ || jsonb_build_object('ops', n); smp := smp || jsonb_build_object('ops', k);
  select * into c from console.customers where id = cid;
  return jsonb_build_object('real', real_, 'sample', smp, 'staff', console.is_staff(),
    'admin', jsonb_build_object(
      'company', c.name, 'logo', coalesce(c.logo_url, '') <> '',
      'details', (select count(*) from unnest(array[c.legal_name, c.tax_id, c.address, c.city, c.state, c.postal_code, c.contact_phone]) v where coalesce(v, '') <> ''),
      'users', (select count(*) from console.customer_members where customer_id = cid),
      'invoices', (select count(*) from console.invoices where customer_id = cid),
      'payments', (select count(*) from console.payments p join console.invoices i on i.id = p.invoice_id where i.customer_id = cid)));
end $$;
revoke all on function public.kmr_grand_overview(text) from public, anon;
grant execute on function public.kmr_grand_overview(text) to authenticated;

create or replace function public.kmr_grand_real_export(p_slug text) returns jsonb
language plpgsql stable security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); apps jsonb := '{}'; t text;
begin
  foreach t in array array['hrm','pd','capacity'] loop
    if console.grand_ref(cid, t) is not null then apps := apps || jsonb_build_object(t, public.kmr_data_export(p_slug, t)); end if;
  end loop;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    apps := apps || jsonb_build_object('balloon', public.kmr_balloon_own_export(p_slug));
  end if;
  foreach t in array array['sales','calib','apqp','ppap','rmp','mmd','mnt'] loop
    if console.has_app(cid, t) then apps := apps || jsonb_build_object(t, jsonb_build_object('format', 'kmr-app-real', 'tables', console.app2_export(t, cid, true))); end if;
  end loop;
  apps := apps || jsonb_build_object('ops', jsonb_build_object('format', 'kmr-ops-own', 'records',
    coalesce((select jsonb_agg(jsonb_build_object('kind', r.kind, 'code', r.code, 'name', r.name, 'data', r.data, 'active', r.active) order by r.kind, r.code)
                from console.ops_records r where r.customer_id = cid and not r.sample), '[]')));
  return jsonb_build_object('format', 'kmr-real-data', 'version', 1, 'company', lower(p_slug), 'exported_at', now(), 'apps', apps);
end $$;
revoke all on function public.kmr_grand_real_export(text) from public, anon;
grant execute on function public.kmr_grand_real_export(text) to authenticated;

create or replace function public.kmr_grand_real_flush(p_slug text) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; r uuid; t text; n int;
begin
  r := console.grand_ref(cid, 'hrm');
  if r is not null then
    out := out || jsonb_build_object('hrm_candidates', console.grand_hrm_real_candidates(r));
    out := out || jsonb_build_object('hrm', hrm.real_flush(r));
  end if;
  if console.grand_ref(cid, 'balloon') is not null and to_regclass('public.bi_reports') is not null then
    out := out || jsonb_build_object('balloon', public.kmr_balloon_own_flush(p_slug));
  end if;
  foreach t in array array['pd','capacity'] loop
    r := console.grand_ref(cid, t);
    if r is not null then out := out || jsonb_build_object(t, console.data_clear(t, cid, r)); end if;
  end loop;
  -- Sales Flow / Calibration Hub: count the parent records (plan lines, instruments) removed, sample ones stay
  if console.has_app(cid, 'sales') then
    select count(*) into n from console.sf_lines where customer_id = cid and not sample;
    perform console.app2_clear('sales', cid, true); out := out || jsonb_build_object('sales', n);
  end if;
  if console.has_app(cid, 'calib') then
    select count(*) into n from console.cal_instruments where customer_id = cid and not sample;
    perform console.app2_clear('calib', cid, true); out := out || jsonb_build_object('calib', n);
  end if;
  if console.has_app(cid, 'apqp') then
    select count(*) into n from console.apqp_projects where customer_id = cid and not sample;
    perform console.app2_clear('apqp', cid, true); out := out || jsonb_build_object('apqp', n);
  end if;
  if console.has_app(cid, 'ppap') then
    select count(*) into n from console.ppap_submissions where customer_id = cid and not sample;
    perform console.app2_clear('ppap', cid, true); out := out || jsonb_build_object('ppap', n);
  end if;
  if console.has_app(cid, 'rmp') then
    select count(*) into n from console.rmp_stock where customer_id = cid and not sample;
    perform console.app2_clear('rmp', cid, true); out := out || jsonb_build_object('rmp', n);
  end if;
  if console.has_app(cid, 'mmd') then
    select count(*) into n from console.mmd_route_sheets where customer_id = cid and not sample;
    perform console.app2_clear('mmd', cid, true); out := out || jsonb_build_object('mmd', n);
  end if;
  if console.has_app(cid, 'mnt') then
    select count(*) into n from console.mnt_breakdowns where customer_id = cid and not sample;
    perform console.app2_clear('mnt', cid, true); out := out || jsonb_build_object('mnt', n);
  end if;
  delete from console.ops_records where customer_id = cid and not sample; get diagnostics n = row_count;
  return out || jsonb_build_object('ops', n);
end $$;
revoke all on function public.kmr_grand_real_flush(text) from public, anon;
grant execute on function public.kmr_grand_real_flush(text) to authenticated;

create or replace function public.kmr_grand_real_import(p_slug text, p_data jsonb) returns jsonb
language plpgsql security definer set search_path = console, public as $$
declare cid uuid := console.grand_customer(p_slug); out jsonb := '{}'; t text; a jsonb; n int; me text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if p_data ->> 'format' is distinct from 'kmr-real-data' then raise exception 'This is not a Grand Master real-data file.'; end if;
  if lower(coalesce(p_data ->> 'company', '')) <> lower(p_slug) then
    raise exception 'This file is a backup of another company (%).', p_data ->> 'company';
  end if;
  foreach t in array array['hrm','pd','capacity'] loop
    a := p_data -> 'apps' -> t;
    if a is null or console.grand_ref(cid, t) is null then continue; end if;
    out := out || jsonb_build_object(t, public.kmr_data_import(p_slug, t, a) -> 'restored');
    if t = 'hrm' then
      select count(*) into n from hrm.employees where tenant_id = console.grand_ref(cid, 'hrm') and coalesce(email, '') not like '%@demo.kmr.test';
      out := out || jsonb_build_object('hrm', n, 'hrm_candidates', console.grand_hrm_real_candidates(console.grand_ref(cid, 'hrm')));
    end if;
  end loop;
  a := p_data -> 'apps' -> 'balloon';
  if a is not null and console.grand_ref(cid, 'balloon') is not null then
    perform public.kmr_balloon_own_flush(p_slug);
    if jsonb_array_length(coalesce(a -> 'tables' -> 'bi_reports', '[]')) > 0 then
      out := out || jsonb_build_object('balloon', public.kmr_balloon_own_load(p_slug, a));
    else out := out || jsonb_build_object('balloon', 0); end if;
  end if;
  -- Operations Master before Sales Flow / Calibration Hub (they point at its parts and gauges by code)
  a := p_data -> 'apps' -> 'ops';
  if a is not null then
    delete from console.ops_records where customer_id = cid and not sample;
    insert into console.ops_records (customer_id, kind, code, name, data, active, sample, updated_by)
    select cid, x ->> 'kind', x ->> 'code', coalesce(x ->> 'name', x ->> 'code'), coalesce(x -> 'data', '{}'), coalesce((x ->> 'active')::boolean, true), false, me
      from jsonb_array_elements(coalesce(a -> 'records', '[]')) x
     where coalesce(x ->> 'kind', '') <> '' and coalesce(x ->> 'code', '') <> ''
    on conflict (customer_id, kind, code) do update set name = excluded.name, data = excluded.data, active = excluded.active, sample = false, updated_by = me;
    get diagnostics n = row_count; out := out || jsonb_build_object('ops', n);
  end if;
  foreach t in array array['sales','calib','apqp','ppap','rmp','mmd','mnt'] loop
    a := p_data -> 'apps' -> t;
    if a is null or not console.has_app(cid, t) then continue; end if;
    perform console.app2_restore(t, cid, a -> 'tables', true);
    if t = 'sales' then select count(*) into n from console.sf_lines where customer_id = cid and not sample;
    elsif t = 'calib' then select count(*) into n from console.cal_instruments where customer_id = cid and not sample;
    elsif t = 'apqp' then select count(*) into n from console.apqp_projects where customer_id = cid and not sample;
    elsif t = 'ppap' then select count(*) into n from console.ppap_submissions where customer_id = cid and not sample;
    elsif t = 'rmp' then select count(*) into n from console.rmp_stock where customer_id = cid and not sample;
    elsif t = 'mmd' then select count(*) into n from console.mmd_route_sheets where customer_id = cid and not sample;
    else select count(*) into n from console.mnt_breakdowns where customer_id = cid and not sample; end if;
    out := out || jsonb_build_object(t, n);
  end loop;
  return out;
end $$;
revoke all on function public.kmr_grand_real_import(text, jsonb) from public, anon;
grant execute on function public.kmr_grand_real_import(text, jsonb) to authenticated;

-- the demo workspace switches Maintenance on too
drop function if exists console.demo_refresh(uuid, boolean);
create or replace function console.demo_refresh(p_cid uuid, p_full boolean default true) returns jsonb language plpgsql security definer set search_path = console, public as $$
declare cu console.customers%rowtype; pcode text; out jsonb;
begin
  select * into cu from console.customers where id = p_cid and kind = 'demo';
  if not found then raise exception 'This is not a demo workspace.'; end if;
  foreach pcode in array array['sales', 'calib', 'apqp', 'ppap', 'rmp', 'mmd', 'mnt'] loop
    insert into console.licences (customer_id, product_code, status, valid_until, seats, notes, product_ref, product_slug)
    select p_cid, pcode, 'active', null, 25, 'KMR demo data', p_cid, cu.slug where exists (select 1 from console.products pr where pr.code = pcode)
    on conflict (customer_id, product_code) do nothing;
  end loop;
  perform set_config('request.jwt.claims', jsonb_build_object('role', 'authenticated', 'email', lower(coalesce(cu.contact_email, ''))) ::text, true);
  if p_full then perform public.kmr_grand_sample(cu.slug, 'flush'); end if;   -- the nightly reset starts clean; the first load only adds what is missing
  out := public.kmr_grand_sample(cu.slug, 'load');
  return out;
end $$;
revoke all on function console.demo_refresh(uuid, boolean), console.demo_refresh_all() from public, anon, authenticated;
grant execute on function console.demo_refresh(uuid, boolean), console.demo_refresh_all() to service_role;

do $$ declare f record; begin
  for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname ~ '^kmr_mnt_' loop
    execute format('revoke all on function %s from public, anon', f.sig);
    execute format('grant execute on function %s to authenticated', f.sig);
  end loop;
end $$;

